DELETE FROM nameTable;
INSERT INTO nameTable (id,item) VALUES (1,"Root");
INSERT INTO nameTable (id,item) VALUES (2,"Matte");
INSERT INTO nameTable (id,item) VALUES (3,"Fysik");
INSERT INTO nameTable (id,item) VALUES (4,"Kemi");
INSERT INTO nameTable (id,item) VALUES (5,"Biologi");
INSERT INTO nameTable (id,item) VALUES (6,"Geografi");
INSERT INTO nameTable (id,item) VALUES (7,"Historia");
INSERT INTO nameTable (id,item) VALUES (8,"Religion");
INSERT INTO nameTable (id,item) VALUES (9,"Samhälle");
INSERT INTO nameTable (id,item) VALUES (10,"ax+b");
INSERT INTO nameTable (id,item) VALUES (11,"ax²+bx+c");
INSERT INTO nameTable (id,item) VALUES (12,"ax³+bx²+cx+d");
INSERT INTO nameTable (id,item) VALUES (13,"lg(x)");
INSERT INTO nameTable (id,item) VALUES (14,"sin(x)");
INSERT INTO nameTable (id,item) VALUES (15,"tan(x)");
INSERT INTO nameTable (id,item) VALUES (16,"!");
INSERT INTO nameTable (id,item) VALUES (17,"(1) Linje");
INSERT INTO nameTable (id,item) VALUES (18,"(3) Triangel");
INSERT INTO nameTable (id,item) VALUES (19,"(4) Fyrhörning");
INSERT INTO nameTable (id,item) VALUES (20,"(...) Polygon");
INSERT INTO nameTable (id,item) VALUES (21,"Cirkel");
INSERT INTO nameTable (id,item) VALUES (22,"Hyperbel");
INSERT INTO nameTable (id,item) VALUES (23,"(H) Väte");
INSERT INTO nameTable (id,item) VALUES (24,"(He) Helium");
INSERT INTO nameTable (id,item) VALUES (25,"(Li) Litium");
INSERT INTO nameTable (id,item) VALUES (26,"(Be) Beryllium");
INSERT INTO nameTable (id,item) VALUES (27,"(B) Bor");
INSERT INTO nameTable (id,item) VALUES (28,"(C) Kol");
INSERT INTO nameTable (id,item) VALUES (29,"(N) Kväve");
INSERT INTO nameTable (id,item) VALUES (30,"(O) Syre");
INSERT INTO nameTable (id,item) VALUES (31,"(F) Flour");
INSERT INTO nameTable (id,item) VALUES (32,"(Ne) Neon");
INSERT INTO nameTable (id,item) VALUES (33,"(Na) Natrium");
INSERT INTO nameTable (id,item) VALUES (34,"(Mg) Magnesium");
INSERT INTO nameTable (id,item) VALUES (35,"(Al) Aluminium");
INSERT INTO nameTable (id,item) VALUES (36,"(Si) Kisel");
INSERT INTO nameTable (id,item) VALUES (37,"(P) Fosfor");
INSERT INTO nameTable (id,item) VALUES (38,"(S) Svavel");
INSERT INTO nameTable (id,item) VALUES (39,"(Cl) Klor");
INSERT INTO nameTable (id,item) VALUES (40,"(Ar) Argon");
INSERT INTO nameTable (id,item) VALUES (41,"Kolväte");
INSERT INTO nameTable (id,item) VALUES (42,"(-OH) Alkohol");
INSERT INTO nameTable (id,item) VALUES (43,"Gummi");
INSERT INTO nameTable (id,item) VALUES (44,"Fiber");
INSERT INTO nameTable (id,item) VALUES (45,"Plast");
INSERT INTO nameTable (id,item) VALUES (46,"Lipid (Fett)");
INSERT INTO nameTable (id,item) VALUES (47,"Kolhydrater");
INSERT INTO nameTable (id,item) VALUES (48,"Glykos");
INSERT INTO nameTable (id,item) VALUES (49,"Fruktos");
INSERT INTO nameTable (id,item) VALUES (50,"Stäkelse");
INSERT INTO nameTable (id,item) VALUES (51,"Tensid");
INSERT INTO nameTable (id,item) VALUES (52,"Protein");
INSERT INTO nameTable (id,item) VALUES (53,"Enzym");
INSERT INTO nameTable (id,item) VALUES (54,"Vitamin");
INSERT INTO nameTable (id,item) VALUES (55,"Vitamin");
INSERT INTO nameTable (id,item) VALUES (56,"DNA");
INSERT INTO nameTable (id,item) VALUES (57,"Läkemedel");
INSERT INTO nameTable (id,item) VALUES (58,"Giftiga ämnen");
INSERT INTO nameTable (id,item) VALUES (59,"Algebra");
INSERT INTO nameTable (id,item) VALUES (60,"Geometri");
INSERT INTO nameTable (id,item) VALUES (61,"Analytisk geometri");
INSERT INTO nameTable (id,item) VALUES (62,"Objektegenskap");
INSERT INTO nameTable (id,item) VALUES (63,"Position och vinklar");
INSERT INTO nameTable (id,item) VALUES (64,"Former");
INSERT INTO nameTable (id,item) VALUES (65,"Färg");
INSERT INTO nameTable (id,item) VALUES (66,"Textur");
INSERT INTO nameTable (id,item) VALUES (67,"(x, y, z, α)(bred, höjd, längd)");
INSERT INTO nameTable (id,item) VALUES (68,"Gul");
INSERT INTO nameTable (id,item) VALUES (69,"Röd");
INSERT INTO nameTable (id,item) VALUES (70,"Grön");
INSERT INTO nameTable (id,item) VALUES (71,"Blå");
INSERT INTO nameTable (id,item) VALUES (72,"Grå");
INSERT INTO nameTable (id,item) VALUES (73,"Svart");
INSERT INTO nameTable (id,item) VALUES (74,"Vit");
INSERT INTO nameTable (id,item) VALUES (75,"Brun");
INSERT INTO nameTable (id,item) VALUES (76,"Orange");
INSERT INTO nameTable (id,item) VALUES (77,"Lila");
INSERT INTO nameTable (id,item) VALUES (78,"Beige");
INSERT INTO nameTable (id,item) VALUES (79,"Turkos");
INSERT INTO nameTable (id,item) VALUES (80,"Kaki");
INSERT INTO nameTable (id,item) VALUES (81,"Akvamarin");
INSERT INTO nameTable (id,item) VALUES (82,"Crimson");
INSERT INTO nameTable (id,item) VALUES (83,"Cream");
INSERT INTO nameTable (id,item) VALUES (84,"Scarlet");
INSERT INTO nameTable (id,item) VALUES (85,"Fyllning");
INSERT INTO nameTable (id,item) VALUES (86,"Gräns");
INSERT INTO nameTable (id,item) VALUES (87,"Skugga/Glöd");
INSERT INTO nameTable (id,item) VALUES (88,"Hård");
INSERT INTO nameTable (id,item) VALUES (89,"Grov");
INSERT INTO nameTable (id,item) VALUES (90,"Mjuk");
INSERT INTO nameTable (id,item) VALUES (91,"Slät");
INSERT INTO nameTable (id,item) VALUES (92,"Spetsig");
INSERT INTO nameTable (id,item) VALUES (93,"Ojämn");
INSERT INTO nameTable (id,item) VALUES (94,"⊥: a1*a2 = -1");
INSERT INTO nameTable (id,item) VALUES (95,"∥: a1 = a2");
INSERT INTO nameTable (id,item) VALUES (96,"^B=^C");
INSERT INTO nameTable (id,item) VALUES (97,"AB=AC");
INSERT INTO nameTable (id,item) VALUES (98,"^=60°/=");
INSERT INTO nameTable (id,item) VALUES (99,"AB∥CD & AC∥BD");
INSERT INTO nameTable (id,item) VALUES (100,"^A = ^D & ^B = ^C");
INSERT INTO nameTable (id,item) VALUES (101,"x=(-b+√(b²-4ac)");
INSERT INTO nameTable (id,item) VALUES (102,"Kvadreringsregler");
INSERT INTO nameTable (id,item) VALUES (103,"(a+b)²=a²+2ab+b²");
INSERT INTO nameTable (id,item) VALUES (104,"(a-b)²=a²-2ab+b²");
INSERT INTO nameTable (id,item) VALUES (105,"lg(ab) = lg(a)+lg(b)");
INSERT INTO nameTable (id,item) VALUES (106,"a/sin(A) = b/sin(B) = c/sin(C)");
INSERT INTO nameTable (id,item) VALUES (107,"sin²(x)+cos²(x)=1");
INSERT INTO nameTable (id,item) VALUES (108,"c²=a²+b²-2abcos(C)");
INSERT INTO nameTable (id,item) VALUES (109,"nPr=n!/(n-r)!");
INSERT INTO nameTable (id,item) VALUES (110,"nCr=nPr/r!");
INSERT INTO nameTable (id,item) VALUES (111,"∫");
INSERT INTO nameTable (id,item) VALUES (112,"Δ/Δt");
INSERT INTO nameTable (id,item) VALUES (113,"Δ/Δx(ax^b) = abx^(b-1)");
INSERT INTO nameTable (id,item) VALUES (114,"Jorden");
INSERT INTO nameTable (id,item) VALUES (115,"Luft");
INSERT INTO nameTable (id,item) VALUES (116,"Jord");
INSERT INTO nameTable (id,item) VALUES (117,"Marknivå");
INSERT INTO nameTable (id,item) VALUES (118,"Vatten");
INSERT INTO nameTable (id,item) VALUES (119,"Naturresurser");
INSERT INTO nameTable (id,item) VALUES (120,"Miljö och klimat");
INSERT INTO nameTable (id,item) VALUES (121,"Atmosfär");
INSERT INTO nameTable (id,item) VALUES (122,"Troposfär (11km)");
INSERT INTO nameTable (id,item) VALUES (123,"Stratosfär (30km)");
INSERT INTO nameTable (id,item) VALUES (124,"Jonosfär (100km)");
INSERT INTO nameTable (id,item) VALUES (125,"Inre krafter");
INSERT INTO nameTable (id,item) VALUES (126,"Yttre krafter");
INSERT INTO nameTable (id,item) VALUES (127,"Vulkanism");
INSERT INTO nameTable (id,item) VALUES (128,"Sprickor");
INSERT INTO nameTable (id,item) VALUES (129,"Mantel");
INSERT INTO nameTable (id,item) VALUES (130,"Magma");
INSERT INTO nameTable (id,item) VALUES (131,"Förvittring");
INSERT INTO nameTable (id,item) VALUES (132,"Deposition");
INSERT INTO nameTable (id,item) VALUES (133,"Jordbävning");
INSERT INTO nameTable (id,item) VALUES (134,"sprucken jord");
INSERT INTO nameTable (id,item) VALUES (135,"Kontinentaldrift");
INSERT INTO nameTable (id,item) VALUES (136,"Berggrund");
INSERT INTO nameTable (id,item) VALUES (137,"Granit");
INSERT INTO nameTable (id,item) VALUES (138,"Sandsten");
INSERT INTO nameTable (id,item) VALUES (139,"Gnejs");
INSERT INTO nameTable (id,item) VALUES (140,"Olja(Petroleum)");
INSERT INTO nameTable (id,item) VALUES (141,"Gas");
INSERT INTO nameTable (id,item) VALUES (142,"Kol");
INSERT INTO nameTable (id,item) VALUES (143,"Mineraler");
INSERT INTO nameTable (id,item) VALUES (144,"Sand");
INSERT INTO nameTable (id,item) VALUES (145,"Sten");
INSERT INTO nameTable (id,item) VALUES (146,"Vatten");
INSERT INTO nameTable (id,item) VALUES (147,"Mark");
INSERT INTO nameTable (id,item) VALUES (148,"Högre temperatur");
INSERT INTO nameTable (id,item) VALUES (149,"Högre halt koldioxid");
INSERT INTO nameTable (id,item) VALUES (150,"Extrem klimat");
INSERT INTO nameTable (id,item) VALUES (151,"Vattenbrist");
INSERT INTO nameTable (id,item) VALUES (152,"Verktyg");
INSERT INTO nameTable (id,item) VALUES (153,"Penna");
INSERT INTO nameTable (id,item) VALUES (154,"Blyertspenna");
INSERT INTO nameTable (id,item) VALUES (155,"Pensel");
INSERT INTO nameTable (id,item) VALUES (156,"Skrivande");
INSERT INTO nameTable (id,item) VALUES (157,"Märkpenna");
INSERT INTO nameTable (id,item) VALUES (158,"Bläck");
INSERT INTO nameTable (id,item) VALUES (159,"Borttagande");
INSERT INTO nameTable (id,item) VALUES (160,"Suddgummi");
INSERT INTO nameTable (id,item) VALUES (161,"Tipex");
INSERT INTO nameTable (id,item) VALUES (162,"Korrektionspenna");
INSERT INTO nameTable (id,item) VALUES (163,"Yta");
INSERT INTO nameTable (id,item) VALUES (164,"Andra verktyg");
INSERT INTO nameTable (id,item) VALUES (165,"Papper");
INSERT INTO nameTable (id,item) VALUES (166,"Skrivbok");
INSERT INTO nameTable (id,item) VALUES (167,"Tavla");
INSERT INTO nameTable (id,item) VALUES (168,"Pennvässare");
INSERT INTO nameTable (id,item) VALUES (169,"Linjal");
INSERT INTO nameTable (id,item) VALUES (170,"Cirkelpassare");
INSERT INTO nameTable (id,item) VALUES (171,"Klämmor");
INSERT INTO nameTable (id,item) VALUES (172,"Häftare");
INSERT INTO nameTable (id,item) VALUES (173,"Dator");
INSERT INTO nameTable (id,item) VALUES (174,"GUI");
INSERT INTO nameTable (id,item) VALUES (175,"Hårdvaror");
INSERT INTO nameTable (id,item) VALUES (176,"Lagring");
INSERT INTO nameTable (id,item) VALUES (177,"Typer");
INSERT INTO nameTable (id,item) VALUES (178,"Mjukvaror");
INSERT INTO nameTable (id,item) VALUES (179,"CoordinatorLayout");
INSERT INTO nameTable (id,item) VALUES (180,"LinearLayout");
INSERT INTO nameTable (id,item) VALUES (181,"Text");
INSERT INTO nameTable (id,item) VALUES (182,"Img");
INSERT INTO nameTable (id,item) VALUES (183,"Knapplista");
INSERT INTO nameTable (id,item) VALUES (184,"Tabell");
INSERT INTO nameTable (id,item) VALUES (185,"Form");
INSERT INTO nameTable (id,item) VALUES (186,"Sidorad");
INSERT INTO nameTable (id,item) VALUES (187,"Header");
INSERT INTO nameTable (id,item) VALUES (188,"Lightbox");
INSERT INTO nameTable (id,item) VALUES (189,"Inmatning");
INSERT INTO nameTable (id,item) VALUES (190,"Välj");
INSERT INTO nameTable (id,item) VALUES (191,"Kryssruta");
INSERT INTO nameTable (id,item) VALUES (192,"Markör");
INSERT INTO nameTable (id,item) VALUES (193,"Upplösning");
INSERT INTO nameTable (id,item) VALUES (194,"Processor");
INSERT INTO nameTable (id,item) VALUES (195,"CPU");
INSERT INTO nameTable (id,item) VALUES (196,"Grafik");
INSERT INTO nameTable (id,item) VALUES (197,"Nätverk");
INSERT INTO nameTable (id,item) VALUES (198,"Powersupply");
INSERT INTO nameTable (id,item) VALUES (199,"RAM");
INSERT INTO nameTable (id,item) VALUES (200,"Hårddisk");
INSERT INTO nameTable (id,item) VALUES (201,"Databas");
INSERT INTO nameTable (id,item) VALUES (202,"Mapp");
INSERT INTO nameTable (id,item) VALUES (203,"Fil");
INSERT INTO nameTable (id,item) VALUES (204,"Genväg");
INSERT INTO nameTable (id,item) VALUES (205,"Ikon");
INSERT INTO nameTable (id,item) VALUES (206,"Verktygsfält");
INSERT INTO nameTable (id,item) VALUES (207,"Stationär Dator");
INSERT INTO nameTable (id,item) VALUES (208,"Bärbar dator");
INSERT INTO nameTable (id,item) VALUES (209,"Surfplatta(Padda)");
INSERT INTO nameTable (id,item) VALUES (210,"Mobiltelefon");
INSERT INTO nameTable (id,item) VALUES (211,"Smartklocka");
INSERT INTO nameTable (id,item) VALUES (212,"Robot");
INSERT INTO nameTable (id,item) VALUES (213,"Superdator");
INSERT INTO nameTable (id,item) VALUES (214,"Mainframe");
INSERT INTO nameTable (id,item) VALUES (215,"Programmeringspråk");
INSERT INTO nameTable (id,item) VALUES (216,"Datastruktur");
INSERT INTO nameTable (id,item) VALUES (217,"Algorithm");
INSERT INTO nameTable (id,item) VALUES (218,"Vapen");
INSERT INTO nameTable (id,item) VALUES (219,"Knivform");
INSERT INTO nameTable (id,item) VALUES (220,"Kniv");
INSERT INTO nameTable (id,item) VALUES (221,"Machete");
INSERT INTO nameTable (id,item) VALUES (222,"Svärd");
INSERT INTO nameTable (id,item) VALUES (223,"Sabel");
INSERT INTO nameTable (id,item) VALUES (224,"Spear");
INSERT INTO nameTable (id,item) VALUES (225,"Hammare");
INSERT INTO nameTable (id,item) VALUES (226,"Ringform");
INSERT INTO nameTable (id,item) VALUES (227,"Yxform");
INSERT INTO nameTable (id,item) VALUES (228,"Mekanisk Skjutvapen");
INSERT INTO nameTable (id,item) VALUES (229,"Advancerad Mekanisk Skjutvapen");
INSERT INTO nameTable (id,item) VALUES (230,"Skjutvapen");
INSERT INTO nameTable (id,item) VALUES (231,"Bombform");
INSERT INTO nameTable (id,item) VALUES (232,"Knuckles-metall");
INSERT INTO nameTable (id,item) VALUES (233,"Shuriken");
INSERT INTO nameTable (id,item) VALUES (234,"Lasso");
INSERT INTO nameTable (id,item) VALUES (235,"Nunchaku");
INSERT INTO nameTable (id,item) VALUES (236,"Yxa");
INSERT INTO nameTable (id,item) VALUES (237,"Tomahawk");
INSERT INTO nameTable (id,item) VALUES (238,"Mace");
INSERT INTO nameTable (id,item) VALUES (239,"Pilbåge");
INSERT INTO nameTable (id,item) VALUES (240,"Pil");
INSERT INTO nameTable (id,item) VALUES (241,"Armborst");
INSERT INTO nameTable (id,item) VALUES (242,"Katapult");
INSERT INTO nameTable (id,item) VALUES (243,"Bajonett");
INSERT INTO nameTable (id,item) VALUES (244,"Ballista");
INSERT INTO nameTable (id,item) VALUES (245,"Harpun");
INSERT INTO nameTable (id,item) VALUES (246,"Arquebus");
INSERT INTO nameTable (id,item) VALUES (247,"Molotov coctail");
INSERT INTO nameTable (id,item) VALUES (248,"Hantverk");
INSERT INTO nameTable (id,item) VALUES (249,"Fordon");
INSERT INTO nameTable (id,item) VALUES (250,"Reparera");
INSERT INTO nameTable (id,item) VALUES (251,"Typer");
INSERT INTO nameTable (id,item) VALUES (252,"Bilar");
INSERT INTO nameTable (id,item) VALUES (253,"Motorcyklar");
INSERT INTO nameTable (id,item) VALUES (254,"Fyrhjulingar");
INSERT INTO nameTable (id,item) VALUES (255,"Husvagnar");
INSERT INTO nameTable (id,item) VALUES (256,"Lastbilar");
INSERT INTO nameTable (id,item) VALUES (257,"Vattenscooter");
INSERT INTO nameTable (id,item) VALUES (258,"Gamla");
INSERT INTO nameTable (id,item) VALUES (259,"Lyx");
INSERT INTO nameTable (id,item) VALUES (260,"Exotisk");
INSERT INTO nameTable (id,item) VALUES (261,"Staden");
INSERT INTO nameTable (id,item) VALUES (262,"Regering");
INSERT INTO nameTable (id,item) VALUES (263,"Ekonomi");
INSERT INTO nameTable (id,item) VALUES (264,"Marknad");
INSERT INTO nameTable (id,item) VALUES (265,"Utbilding");
INSERT INTO nameTable (id,item) VALUES (266,"Arbetsplats");
INSERT INTO nameTable (id,item) VALUES (267,"Underhållning");
INSERT INTO nameTable (id,item) VALUES (268,"Boende");
INSERT INTO nameTable (id,item) VALUES (269,"Kulturer");
INSERT INTO nameTable (id,item) VALUES (270,"Turist");
INSERT INTO nameTable (id,item) VALUES (271,"Advokat");
INSERT INTO nameTable (id,item) VALUES (272,"Ambassad");
INSERT INTO nameTable (id,item) VALUES (273,"Kommun");
INSERT INTO nameTable (id,item) VALUES (274,"Lokalförvaltningskontor");
INSERT INTO nameTable (id,item) VALUES (275,"Tingshuspolisen");
INSERT INTO nameTable (id,item) VALUES (276,"Försäkring");
INSERT INTO nameTable (id,item) VALUES (277,"Resebyrå");
INSERT INTO nameTable (id,item) VALUES (278,"Bank");
INSERT INTO nameTable (id,item) VALUES (279,"ATM");
INSERT INTO nameTable (id,item) VALUES (280,"Köpcentrum");
INSERT INTO nameTable (id,item) VALUES (281,"Bokföring");
INSERT INTO nameTable (id,item) VALUES (282,"Postkontor");
INSERT INTO nameTable (id,item) VALUES (283,"Supermarket");
INSERT INTO nameTable (id,item) VALUES (284,"Butik");
INSERT INTO nameTable (id,item) VALUES (285,"Varuhus");
INSERT INTO nameTable (id,item) VALUES (286,"Bageri");
INSERT INTO nameTable (id,item) VALUES (287,"Tvätt");
INSERT INTO nameTable (id,item) VALUES (288,"Skoaffär");
INSERT INTO nameTable (id,item) VALUES (289,"Bilförsäljare");
INSERT INTO nameTable (id,item) VALUES (290,"Bar");
INSERT INTO nameTable (id,item) VALUES (291,"Cafeteria");
INSERT INTO nameTable (id,item) VALUES (292,"Resturang");
INSERT INTO nameTable (id,item) VALUES (293,"Takeaway");
INSERT INTO nameTable (id,item) VALUES (294,"Matleverans");
INSERT INTO nameTable (id,item) VALUES (295,"Bibliotek");
INSERT INTO nameTable (id,item) VALUES (296,"Universitet");
INSERT INTO nameTable (id,item) VALUES (297,"Grundskola");
INSERT INTO nameTable (id,item) VALUES (298,"Gymnasieskola");
INSERT INTO nameTable (id,item) VALUES (299,"Bokaffär");
INSERT INTO nameTable (id,item) VALUES (300,"Låssmed");
INSERT INTO nameTable (id,item) VALUES (301,"Takentreprenör");
INSERT INTO nameTable (id,item) VALUES (302,"Elektriker");
INSERT INTO nameTable (id,item) VALUES (303,"Flyttare");
INSERT INTO nameTable (id,item) VALUES (304,"Järnaffär");
INSERT INTO nameTable (id,item) VALUES (305,"Bensinstation");
INSERT INTO nameTable (id,item) VALUES (306,"Målare");
INSERT INTO nameTable (id,item) VALUES (307,"Reparation");
INSERT INTO nameTable (id,item) VALUES (308,"Kontor");
INSERT INTO nameTable (id,item) VALUES (309,"Datoringengör arbetsplats");
INSERT INTO nameTable (id,item) VALUES (310,"Casino");
INSERT INTO nameTable (id,item) VALUES (311,"Bio");
INSERT INTO nameTable (id,item) VALUES (312,"Night Club");
INSERT INTO nameTable (id,item) VALUES (313,"Stadium");
INSERT INTO nameTable (id,item) VALUES (314,"Filmuthyrning");
INSERT INTO nameTable (id,item) VALUES (315,"Gym");
INSERT INTO nameTable (id,item) VALUES (316,"Fastighetsbyrå");
INSERT INTO nameTable (id,item) VALUES (317,"Förråd");
INSERT INTO nameTable (id,item) VALUES (318,"Begravningsbyrå");
INSERT INTO nameTable (id,item) VALUES (319,"Kyrkogård");
INSERT INTO nameTable (id,item) VALUES (320,"Hotell");
INSERT INTO nameTable (id,item) VALUES (321,"Vandrarhem");
INSERT INTO nameTable (id,item) VALUES (322,"Camping");
INSERT INTO nameTable (id,item) VALUES (323,"Konstgalleri");
INSERT INTO nameTable (id,item) VALUES (324,"Museum");
INSERT INTO nameTable (id,item) VALUES (325,"Kyrka");
INSERT INTO nameTable (id,item) VALUES (326,"Synagoga");
INSERT INTO nameTable (id,item) VALUES (327,"Nöjespark");
INSERT INTO nameTable (id,item) VALUES (328,"Aquarium");
INSERT INTO nameTable (id,item) VALUES (329,"Park");
INSERT INTO nameTable (id,item) VALUES (330,"Camping");
INSERT INTO nameTable (id,item) VALUES (331,"Zoo");
INSERT INTO nameTable (id,item) VALUES (332,"Transport");
INSERT INTO nameTable (id,item) VALUES (333,"Hälsa");
INSERT INTO nameTable (id,item) VALUES (334,"Flygplatsbiluthyrning");
INSERT INTO nameTable (id,item) VALUES (335,"Biltvättstation");
INSERT INTO nameTable (id,item) VALUES (336,"Veterinärsvård");
INSERT INTO nameTable (id,item) VALUES (337,"Tandläkare");
INSERT INTO nameTable (id,item) VALUES (338,"Läkare");
INSERT INTO nameTable (id,item) VALUES (339,"Apotek");
INSERT INTO nameTable (id,item) VALUES (340,"Fysioterapeut");
INSERT INTO nameTable (id,item) VALUES (341,"Sjukhus");
INSERT INTO nameTable (id,item) VALUES (342,"Hemma");
INSERT INTO nameTable (id,item) VALUES (343,"Nivåer");
INSERT INTO nameTable (id,item) VALUES (344,"Rum");
INSERT INTO nameTable (id,item) VALUES (345,"Sovrum");
INSERT INTO nameTable (id,item) VALUES (346,"Badrum");
INSERT INTO nameTable (id,item) VALUES (347,"Kök");
INSERT INTO nameTable (id,item) VALUES (348,"Mottagande hall");
INSERT INTO nameTable (id,item) VALUES (349,"Hemmakontor");
INSERT INTO nameTable (id,item) VALUES (350,"Vardagsrum");
INSERT INTO nameTable (id,item) VALUES (351,"Andra hemutbygnader");
INSERT INTO nameTable (id,item) VALUES (352,"hall");
INSERT INTO nameTable (id,item) VALUES (353,"Källare");
INSERT INTO nameTable (id,item) VALUES (354,"Skorsten");
INSERT INTO nameTable (id,item) VALUES (355,"Tak");
INSERT INTO nameTable (id,item) VALUES (356,"Vägg");
INSERT INTO nameTable (id,item) VALUES (357,"Skåp");
INSERT INTO nameTable (id,item) VALUES (358,"Stol");
INSERT INTO nameTable (id,item) VALUES (359,"Matta");
INSERT INTO nameTable (id,item) VALUES (360,"Lampa");
INSERT INTO nameTable (id,item) VALUES (361,"Fönster");
INSERT INTO nameTable (id,item) VALUES (362,"Bord");
INSERT INTO nameTable (id,item) VALUES (363,"Dator");
INSERT INTO nameTable (id,item) VALUES (364,"Musikuthyrning");
INSERT INTO nameTable (id,item) VALUES (365,"Sänghyllor");
INSERT INTO nameTable (id,item) VALUES (366,"Nattduksbord");
INSERT INTO nameTable (id,item) VALUES (367,"Gaderob");
INSERT INTO nameTable (id,item) VALUES (368,"Skrivbordslampa");
INSERT INTO nameTable (id,item) VALUES (369,"Väckarklocka");
INSERT INTO nameTable (id,item) VALUES (370,"Toalett");
INSERT INTO nameTable (id,item) VALUES (371,"Dusch");
INSERT INTO nameTable (id,item) VALUES (372,"Bad");
INSERT INTO nameTable (id,item) VALUES (373,"Handfat");
INSERT INTO nameTable (id,item) VALUES (374,"Kylskåp");
INSERT INTO nameTable (id,item) VALUES (375,"Ugn");
INSERT INTO nameTable (id,item) VALUES (376,"Mikrovågsugn");
INSERT INTO nameTable (id,item) VALUES (377,"Diskmaskin");
INSERT INTO nameTable (id,item) VALUES (378,"Spisar");
INSERT INTO nameTable (id,item) VALUES (379,"Kåpor-kök");
INSERT INTO nameTable (id,item) VALUES (380,"Krukor");
INSERT INTO nameTable (id,item) VALUES (381,"Glas+Bestick");
INSERT INTO nameTable (id,item) VALUES (382,"Mat");
INSERT INTO nameTable (id,item) VALUES (383,"Matsal");
INSERT INTO nameTable (id,item) VALUES (384,"Dörrmatta");
INSERT INTO nameTable (id,item) VALUES (385,"Klädhylla");
INSERT INTO nameTable (id,item) VALUES (386,"Kommod");
INSERT INTO nameTable (id,item) VALUES (387,"Spegel");
INSERT INTO nameTable (id,item) VALUES (388,"Korridor");
INSERT INTO nameTable (id,item) VALUES (389,"Matta");
INSERT INTO nameTable (id,item) VALUES (390,"TV");
INSERT INTO nameTable (id,item) VALUES (391,"Soffa");
INSERT INTO nameTable (id,item) VALUES (392,"Böcker");
INSERT INTO nameTable (id,item) VALUES (393,"Vas");
INSERT INTO nameTable (id,item) VALUES (394,"Bilder");
INSERT INTO nameTable (id,item) VALUES (395,"Växter(Krukväxter)");
INSERT INTO nameTable (id,item) VALUES (396,"Trädgård");
INSERT INTO nameTable (id,item) VALUES (397,"Pool");
INSERT INTO nameTable (id,item) VALUES (398,"Vindsterrass");
INSERT INTO nameTable (id,item) VALUES (399,"Förråd");
INSERT INTO nameTable (id,item) VALUES (400,"Balkong");
INSERT INTO nameTable (id,item) VALUES (401,"Förvaltning(Administration)");
INSERT INTO nameTable (id,item) VALUES (402,"Vattenfallsmetoden");
INSERT INTO nameTable (id,item) VALUES (403,"Kravspecifikation");
INSERT INTO nameTable (id,item) VALUES (404,"Design");
INSERT INTO nameTable (id,item) VALUES (405,"Konstruktion");
INSERT INTO nameTable (id,item) VALUES (406,"Integration");
INSERT INTO nameTable (id,item) VALUES (407,"Test");
INSERT INTO nameTable (id,item) VALUES (408,"Installation");
INSERT INTO nameTable (id,item) VALUES (409,"Underhåll");
INSERT INTO nameTable (id,item) VALUES (410,"Mjukvaror");
INSERT INTO nameTable (id,item) VALUES (411,"Mjukvaruprojekt");
INSERT INTO nameTable (id,item) VALUES (412,"Spel och datorspel");
INSERT INTO nameTable (id,item) VALUES (413,"Fysisk kondition");
INSERT INTO nameTable (id,item) VALUES (414,"Överlevnad");
INSERT INTO nameTable (id,item) VALUES (415,"Ätbart");
INSERT INTO nameTable (id,item) VALUES (416,"Hasardspel");
INSERT INTO nameTable (id,item) VALUES (417,"Kortspel");
INSERT INTO nameTable (id,item) VALUES (418,"Spelautomater");
INSERT INTO nameTable (id,item) VALUES (419,"Lotteri");
INSERT INTO nameTable (id,item) VALUES (420,"Kasinomarker(Kasinochips)");
INSERT INTO nameTable (id,item) VALUES (421,"Lotteribiljetter");
INSERT INTO nameTable (id,item) VALUES (422,"Spådom");
INSERT INTO nameTable (id,item) VALUES (423,"Astrologi");
INSERT INTO nameTable (id,item) VALUES (424,"Stjärntecken");
INSERT INTO nameTable (id,item) VALUES (425,"Oxen");
INSERT INTO nameTable (id,item) VALUES (426,"Tvillingarna");
INSERT INTO nameTable (id,item) VALUES (427,"Kräftan");
INSERT INTO nameTable (id,item) VALUES (428,"Lejonet");
INSERT INTO nameTable (id,item) VALUES (429,"Jungfrun");
INSERT INTO nameTable (id,item) VALUES (430,"Vågen");
INSERT INTO nameTable (id,item) VALUES (431,"Skorpionen");
INSERT INTO nameTable (id,item) VALUES (432,"Skytten");
INSERT INTO nameTable (id,item) VALUES (433,"Stenbocken");
INSERT INTO nameTable (id,item) VALUES (434,"Vattumannen");
INSERT INTO nameTable (id,item) VALUES (435,"Fiskarna");
INSERT INTO nameTable (id,item) VALUES (436,"Tarot");
INSERT INTO nameTable (id,item) VALUES (437,"Astronomi");
INSERT INTO nameTable (id,item) VALUES (438,"Stel mekanik");
INSERT INTO nameTable (id,item) VALUES (439,"Vätskemekanik");
INSERT INTO nameTable (id,item) VALUES (440,"Elektricitet");
INSERT INTO nameTable (id,item) VALUES (441,"Vågor");
INSERT INTO nameTable (id,item) VALUES (442,"Termodynamik(Värme)");
INSERT INTO nameTable (id,item) VALUES (443,"Kärnfysik(Atomer)");
INSERT INTO nameTable (id,item) VALUES (444,"P=E/t");
INSERT INTO nameTable (id,item) VALUES (445,"E=F*s");
INSERT INTO nameTable (id,item) VALUES (446,"F=GMm/r²");
INSERT INTO nameTable (id,item) VALUES (447,"F=ma");
INSERT INTO nameTable (id,item) VALUES (448,"τ=Fr*sin(α)");
INSERT INTO nameTable (id,item) VALUES (449,"τ=Iα");
INSERT INTO nameTable (id,item) VALUES (450,"Laminär");
INSERT INTO nameTable (id,item) VALUES (451,"Turbulens");
INSERT INTO nameTable (id,item) VALUES (452,"ρ=mV");
INSERT INTO nameTable (id,item) VALUES (453,"F1A1=F2A2");
INSERT INTO nameTable (id,item) VALUES (454,"Q=dVdt");
INSERT INTO nameTable (id,item) VALUES (455,"A1v1=A2v2");
INSERT INTO nameTable (id,item) VALUES (456,"P=IV");
INSERT INTO nameTable (id,item) VALUES (457,"F=qvB*sin(α)");
INSERT INTO nameTable (id,item) VALUES (458,"ΣU=ΣIR");
INSERT INTO nameTable (id,item) VALUES (459,"Q=CV");
INSERT INTO nameTable (id,item) VALUES (460,"τ=RC");
INSERT INTO nameTable (id,item) VALUES (461,"ε=Φ/t");
INSERT INTO nameTable (id,item) VALUES (462,"F=-kx");
INSERT INTO nameTable (id,item) VALUES (463,"I=P/A");
INSERT INTO nameTable (id,item) VALUES (464,"1/o + 1/i = 1/f");
INSERT INTO nameTable (id,item) VALUES (465,"Reflektion");
INSERT INTO nameTable (id,item) VALUES (466,"Refraktion");
INSERT INTO nameTable (id,item) VALUES (467,"Diffraktion");
INSERT INTO nameTable (id,item) VALUES (468,"n*sin(α)");
INSERT INTO nameTable (id,item) VALUES (469,"d*sin(α)=mλ");
INSERT INTO nameTable (id,item) VALUES (470,"Ekonomi");
INSERT INTO nameTable (id,item) VALUES (471,"Handel");
INSERT INTO nameTable (id,item) VALUES (472,"Politik");
INSERT INTO nameTable (id,item) VALUES (473,"Flöde");
INSERT INTO nameTable (id,item) VALUES (474,"Tre stora branscher");
INSERT INTO nameTable (id,item) VALUES (475,"Inkomst");
INSERT INTO nameTable (id,item) VALUES (476,"Utgifter");
INSERT INTO nameTable (id,item) VALUES (477,"Kontanter");
INSERT INTO nameTable (id,item) VALUES (478,"Terminskontrakt(Futures)");
INSERT INTO nameTable (id,item) VALUES (479,"Aktie(Stock)");
INSERT INTO nameTable (id,item) VALUES (480,"Kryptovaluta");
INSERT INTO nameTable (id,item) VALUES (481,"Korruption");
INSERT INTO nameTable (id,item) VALUES (482,"Neptism");
INSERT INTO nameTable (id,item) VALUES (483,"Mutor");
INSERT INTO nameTable (id,item) VALUES (484,"Förskingring");
INSERT INTO nameTable (id,item) VALUES (485,"Klassisk ekonomi");
INSERT INTO nameTable (id,item) VALUES (486,"Neoklassisk ekonomi");
INSERT INTO nameTable (id,item) VALUES (487,"1");
INSERT INTO nameTable (id,item) VALUES (488,"1½");
INSERT INTO nameTable (id,item) VALUES (489,"2");
INSERT INTO nameTable (id,item) VALUES (490,"3");
INSERT INTO nameTable (id,item) VALUES (491,"Jordbruk");
INSERT INTO nameTable (id,item) VALUES (492,"Skogsbruk");
INSERT INTO nameTable (id,item) VALUES (493,"Fiske");
INSERT INTO nameTable (id,item) VALUES (494,"Gruvdrift");
INSERT INTO nameTable (id,item) VALUES (495,"Arbetskraft");
INSERT INTO nameTable (id,item) VALUES (496,"Råvaror");
INSERT INTO nameTable (id,item) VALUES (497,"Kunder");
INSERT INTO nameTable (id,item) VALUES (498,"Industri Specialisering");
INSERT INTO nameTable (id,item) VALUES (499,"Livsmedelindustri");
INSERT INTO nameTable (id,item) VALUES (500,"Skogsindustri");
INSERT INTO nameTable (id,item) VALUES (501,"Jord-sten");
INSERT INTO nameTable (id,item) VALUES (502,"Tekoindustri");
INSERT INTO nameTable (id,item) VALUES (503,"Kemiindustri");
INSERT INTO nameTable (id,item) VALUES (504,"Information och tjänster");
INSERT INTO nameTable (id,item) VALUES (505,"Turism");
INSERT INTO nameTable (id,item) VALUES (506,"Handel");
INSERT INTO nameTable (id,item) VALUES (507,"Världshandel");
INSERT INTO nameTable (id,item) VALUES (508,"EU");
INSERT INTO nameTable (id,item) VALUES (509,"NAFTA");
INSERT INTO nameTable (id,item) VALUES (510,"MERCOSUR");
INSERT INTO nameTable (id,item) VALUES (511,"WTO");
INSERT INTO nameTable (id,item) VALUES (512,"Application");
INSERT INTO nameTable (id,item) VALUES (513,"I/O (Input/Output)");
INSERT INTO nameTable (id,item) VALUES (514,"Memory");
INSERT INTO nameTable (id,item) VALUES (515,"Disk");
INSERT INTO nameTable (id,item) VALUES (516,"OS (Operativsystem)");
INSERT INTO nameTable (id,item) VALUES (517,"Kallt vapen");
INSERT INTO nameTable (id,item) VALUES (518,"Hett vapen");
INSERT INTO nameTable (id,item) VALUES (519,"Kärnvapen");
INSERT INTO nameTable (id,item) VALUES (520,"Kemivapen");
INSERT INTO nameTable (id,item) VALUES (521,"Biologivapen");
INSERT INTO nameTable (id,item) VALUES (522,"Pappersverk");
INSERT INTO nameTable (id,item) VALUES (523,"Sågverk");
INSERT INTO nameTable (id,item) VALUES (524,"Rasterisering");
INSERT INTO nameTable (id,item) VALUES (525,"Vetenskaplig Rasterisering");
INSERT INTO nameTable (id,item) VALUES (526,"(x-x0)²+(y-y0)²=r²");
INSERT INTO nameTable (id,item) VALUES (527,"Applikation");
INSERT INTO nameTable (id,item) VALUES (528,"Politisk inriktningar");
INSERT INTO nameTable (id,item) VALUES (529,"Anarkistisk");
INSERT INTO nameTable (id,item) VALUES (530,"Marxist");
INSERT INTO nameTable (id,item) VALUES (531,"Socialistisk");
INSERT INTO nameTable (id,item) VALUES (532,"Liberal");
INSERT INTO nameTable (id,item) VALUES (533,"Konsvervativ");
INSERT INTO nameTable (id,item) VALUES (534,"Monarkistisk");
INSERT INTO nameTable (id,item) VALUES (535,"Fascist");
INSERT INTO nameTable (id,item) VALUES (536,"Svensk politik");
INSERT INTO nameTable (id,item) VALUES (537,"Amerikansk politik");
INSERT INTO nameTable (id,item) VALUES (538,"Statsnivå");
INSERT INTO nameTable (id,item) VALUES (539,"Landstingsnivå (Regionalnivå)");
INSERT INTO nameTable (id,item) VALUES (540,"Kommunalnivå");
INSERT INTO nameTable (id,item) VALUES (541,"Riksdagen");
INSERT INTO nameTable (id,item) VALUES (542,"Regeringen");
INSERT INTO nameTable (id,item) VALUES (543,"Statsministern");
INSERT INTO nameTable (id,item) VALUES (544,"Estetik");
INSERT INTO nameTable (id,item) VALUES (545,"Språk");
INSERT INTO nameTable (id,item) VALUES (546,"Diskussioner");
INSERT INTO nameTable (id,item) VALUES (547,"Utskott");
INSERT INTO nameTable (id,item) VALUES (548,"Departement");
INSERT INTO nameTable (id,item) VALUES (549,"Utrikesdepartement");
INSERT INTO nameTable (id,item) VALUES (550,"Utför besult");
INSERT INTO nameTable (id,item) VALUES (551,"Statliga uppgifter");
INSERT INTO nameTable (id,item) VALUES (552,"Partier");
INSERT INTO nameTable (id,item) VALUES (553,"Kongressen");
INSERT INTO nameTable (id,item) VALUES (554,"Senaten");
INSERT INTO nameTable (id,item) VALUES (555,"Högsta domstolen");
INSERT INTO nameTable (id,item) VALUES (556,"Partier");
INSERT INTO nameTable (id,item) VALUES (557,"Demokraterna");
INSERT INTO nameTable (id,item) VALUES (558,"Republikanerna");
INSERT INTO nameTable (id,item) VALUES (559,"Demografi");
INSERT INTO nameTable (id,item) VALUES (560,"Geografi-politik");
INSERT INTO nameTable (id,item) VALUES (561,"4 Stadier");
INSERT INTO nameTable (id,item) VALUES (562,"Hög föddantal och hög dödsantal");
INSERT INTO nameTable (id,item) VALUES (563,"Hög föddantal och låg dödsantal");
INSERT INTO nameTable (id,item) VALUES (564,"Låg föddantal och låg dödsantal");
INSERT INTO nameTable (id,item) VALUES (565,"Jämn fördelning");
INSERT INTO nameTable (id,item) VALUES (566,"Förflyttning");
INSERT INTO nameTable (id,item) VALUES (567,"Arbete");
INSERT INTO nameTable (id,item) VALUES (568,"Krig");
INSERT INTO nameTable (id,item) VALUES (569,"Förföljelse");
INSERT INTO nameTable (id,item) VALUES (570,"Miljö");
INSERT INTO nameTable (id,item) VALUES (571,"Geografi-ekonomi");
INSERT INTO nameTable (id,item) VALUES (572,"Levnadsstandard (HDI)");
INSERT INTO nameTable (id,item) VALUES (573,"Kapitalism");
INSERT INTO nameTable (id,item) VALUES (574,"Fattigdom");
INSERT INTO nameTable (id,item) VALUES (575,"Idealsamhälle");
INSERT INTO nameTable (id,item) VALUES (576,"Stora ekonomiska klyftor");
INSERT INTO nameTable (id,item) VALUES (577,"Orättvisa villkor");
INSERT INTO nameTable (id,item) VALUES (578,"Resurser bland rika");
INSERT INTO nameTable (id,item) VALUES (579,"Världshandeln gynnar rika");
INSERT INTO nameTable (id,item) VALUES (580,"Sjukdom");
INSERT INTO nameTable (id,item) VALUES (581,"Korruption");
INSERT INTO nameTable (id,item) VALUES (582,"Brist");
INSERT INTO nameTable (id,item) VALUES (583,"Högt befolkad");
INSERT INTO nameTable (id,item) VALUES (584,"Svält");
INSERT INTO nameTable (id,item) VALUES (585,"Jordbrukssamhälle");
INSERT INTO nameTable (id,item) VALUES (586,"Vattenbrist");
INSERT INTO nameTable (id,item) VALUES (587,"Lösningar");
INSERT INTO nameTable (id,item) VALUES (588,"Millenniemål");
INSERT INTO nameTable (id,item) VALUES (589,"Agenda 2030");
INSERT INTO nameTable (id,item) VALUES (590,"Länder");
INSERT INTO nameTable (id,item) VALUES (591,"Konst");
INSERT INTO nameTable (id,item) VALUES (592,"Design");
INSERT INTO nameTable (id,item) VALUES (593,"Litteratur");
INSERT INTO nameTable (id,item) VALUES (594,"Musik");
INSERT INTO nameTable (id,item) VALUES (595,"Arkitektur");
INSERT INTO nameTable (id,item) VALUES (596,"USA");
INSERT INTO nameTable (id,item) VALUES (597,"Japan");
INSERT INTO nameTable (id,item) VALUES (598,"Ryssland");
INSERT INTO nameTable (id,item) VALUES (599,"Bergskedjor vid kuster");
INSERT INTO nameTable (id,item) VALUES (600,"Inre slätter");
INSERT INTO nameTable (id,item) VALUES (601,"Floder");
INSERT INTO nameTable (id,item) VALUES (602,"Översvämningar");
INSERT INTO nameTable (id,item) VALUES (603,"Skolan");
INSERT INTO nameTable (id,item) VALUES (604,"Arbete");
INSERT INTO nameTable (id,item) VALUES (605,"Resa");
INSERT INTO nameTable (id,item) VALUES (606,"Underhållning");
INSERT INTO nameTable (id,item) VALUES (607,"Hobby");
INSERT INTO nameTable (id,item) VALUES (608,"Livsstil");
INSERT INTO nameTable (id,item) VALUES (609,"Privatliv");
INSERT INTO nameTable (id,item) VALUES (610,"Avkopplande Miami");
INSERT INTO nameTable (id,item) VALUES (611,"Modernt");
INSERT INTO nameTable (id,item) VALUES (612,"Klassiskt");
INSERT INTO nameTable (id,item) VALUES (613,"Lantlig");
INSERT INTO nameTable (id,item) VALUES (614,"Sommar");
INSERT INTO nameTable (id,item) VALUES (615,"Vanligt liv");
INSERT INTO nameTable (id,item) VALUES (616,"Tonåringar");
INSERT INTO nameTable (id,item) VALUES (617,"Mot framsteg(bråkmakare)");
INSERT INTO nameTable (id,item) VALUES (618,"Rayan");
INSERT INTO nameTable (id,item) VALUES (619,"Rayan Produktivitet");
INSERT INTO nameTable (id,item) VALUES (620,"Datorspel-livsstil");
INSERT INTO nameTable (id,item) VALUES (621,"Framtidslivsstil");
INSERT INTO nameTable (id,item) VALUES (622,"Minimalism");
INSERT INTO nameTable (id,item) VALUES (623,"metodik");
INSERT INTO nameTable (id,item) VALUES (624,"Tiago-PZK metoden");
INSERT INTO nameTable (id,item) VALUES (625,"Vanlig inlärningsmetoden");
INSERT INTO nameTable (id,item) VALUES (626,"AOORA struktur");
INSERT INTO nameTable (id,item) VALUES (627,"[1 2 3 4 5 6]");
INSERT INTO nameTable (id,item) VALUES (628,"[a1 a2 a3 a4 a5 a6]");
INSERT INTO nameTable (id,item) VALUES (629,"Översikt");
INSERT INTO nameTable (id,item) VALUES (630,"Kunskap");
INSERT INTO nameTable (id,item) VALUES (631,"Med andra");
INSERT INTO nameTable (id,item) VALUES (632,"Profil för samhälle");
INSERT INTO nameTable (id,item) VALUES (633,"Skolämnen");
INSERT INTO nameTable (id,item) VALUES (634,"Träslöjd");
INSERT INTO nameTable (id,item) VALUES (635,"Svenska");
INSERT INTO nameTable (id,item) VALUES (636,"Engelska");
INSERT INTO nameTable (id,item) VALUES (637,"Franska");
INSERT INTO nameTable (id,item) VALUES (638,"Skolämnen");
INSERT INTO nameTable (id,item) VALUES (639,"Uppgifter");
INSERT INTO nameTable (id,item) VALUES (640,"Förhör och prov");
INSERT INTO nameTable (id,item) VALUES (641,"Inga genvägar i skolan");
INSERT INTO nameTable (id,item) VALUES (642,"Aktiviteter");
INSERT INTO nameTable (id,item) VALUES (643,"Grupparbete");
INSERT INTO nameTable (id,item) VALUES (644,"Utflykt");
INSERT INTO nameTable (id,item) VALUES (645,"Studiebesök");
INSERT INTO nameTable (id,item) VALUES (646,"Personer");
INSERT INTO nameTable (id,item) VALUES (647,"Förberedelser");
INSERT INTO nameTable (id,item) VALUES (648,"Struktur (Plan)");
INSERT INTO nameTable (id,item) VALUES (649,"Under resan");
INSERT INTO nameTable (id,item) VALUES (650,"Vart");
INSERT INTO nameTable (id,item) VALUES (651,"Vem");
INSERT INTO nameTable (id,item) VALUES (652,"Hur");
INSERT INTO nameTable (id,item) VALUES (653,"När");
INSERT INTO nameTable (id,item) VALUES (654,"Okända länder");
INSERT INTO nameTable (id,item) VALUES (655,"Kunskap");
INSERT INTO nameTable (id,item) VALUES (656,"Sport");
INSERT INTO nameTable (id,item) VALUES (657,"Natur");
INSERT INTO nameTable (id,item) VALUES (658,"Kultur");
INSERT INTO nameTable (id,item) VALUES (659,"Familj");
INSERT INTO nameTable (id,item) VALUES (660,"Vänner");
INSERT INTO nameTable (id,item) VALUES (661,"Använder pengar");
INSERT INTO nameTable (id,item) VALUES (662,"För mat");
INSERT INTO nameTable (id,item) VALUES (663,"Hur ska man åka?");
INSERT INTO nameTable (id,item) VALUES (664,"Budget");
INSERT INTO nameTable (id,item) VALUES (665,"Transport");
INSERT INTO nameTable (id,item) VALUES (666,"Överlevnad");
INSERT INTO nameTable (id,item) VALUES (667,"Boende");
INSERT INTO nameTable (id,item) VALUES (668,"Resebyrå");
INSERT INTO nameTable (id,item) VALUES (669,"Problem under resan");
INSERT INTO nameTable (id,item) VALUES (670,"Sport");
INSERT INTO nameTable (id,item) VALUES (671,"Struktur");
INSERT INTO nameTable (id,item) VALUES (672,"Typer");
INSERT INTO nameTable (id,item) VALUES (673,"Lag");
INSERT INTO nameTable (id,item) VALUES (674,"Strategi");
INSERT INTO nameTable (id,item) VALUES (675,"Träning");
INSERT INTO nameTable (id,item) VALUES (676,"Kommunikation");
INSERT INTO nameTable (id,item) VALUES (677,"Konversation");
INSERT INTO nameTable (id,item) VALUES (678,"Skämt");
INSERT INTO nameTable (id,item) VALUES (679,"Börjar konversation");
INSERT INTO nameTable (id,item) VALUES (680,"Ändra prattema");
INSERT INTO nameTable (id,item) VALUES (681,"Presentationer");
INSERT INTO nameTable (id,item) VALUES (682,"Psykologi");
INSERT INTO nameTable (id,item) VALUES (683,"Åsikter och tankar");
INSERT INTO nameTable (id,item) VALUES (684,"Personlighet(Karaktär)");
INSERT INTO nameTable (id,item) VALUES (685,"Modig");
INSERT INTO nameTable (id,item) VALUES (686,"Äventyrlig");
INSERT INTO nameTable (id,item) VALUES (687,"Feg");
INSERT INTO nameTable (id,item) VALUES (688,"Självständig");
INSERT INTO nameTable (id,item) VALUES (689,"Bra karaktär");
INSERT INTO nameTable (id,item) VALUES (690,"Dåliga karaktär");
INSERT INTO nameTable (id,item) VALUES (691,"Resurskrik");
INSERT INTO nameTable (id,item) VALUES (692,"Framgångsrik");
INSERT INTO nameTable (id,item) VALUES (693,"Skicklig");
INSERT INTO nameTable (id,item) VALUES (694,"Fantasifull");
INSERT INTO nameTable (id,item) VALUES (695,"Kreativ");
INSERT INTO nameTable (id,item) VALUES (696,"Nyfiken");
INSERT INTO nameTable (id,item) VALUES (697,"Ödmjuk");
INSERT INTO nameTable (id,item) VALUES (698,"Respektfull");
INSERT INTO nameTable (id,item) VALUES (699,"Artig");
INSERT INTO nameTable (id,item) VALUES (700,"Pålitlig");
INSERT INTO nameTable (id,item) VALUES (701,"Ärlig");
INSERT INTO nameTable (id,item) VALUES (702,"Generös");
INSERT INTO nameTable (id,item) VALUES (703,"Lojal");
INSERT INTO nameTable (id,item) VALUES (704,"Patrotisk");
INSERT INTO nameTable (id,item) VALUES (705,"Neutrala karaktär");
INSERT INTO nameTable (id,item) VALUES (706,"Strikt");
INSERT INTO nameTable (id,item) VALUES (707,"Dominerande");
INSERT INTO nameTable (id,item) VALUES (708,"Ledare");
INSERT INTO nameTable (id,item) VALUES (709,"Energisk");
INSERT INTO nameTable (id,item) VALUES (710,"Hoppfull");
INSERT INTO nameTable (id,item) VALUES (711,"Utåtriktad");
INSERT INTO nameTable (id,item) VALUES (712,"Introvert");
INSERT INTO nameTable (id,item) VALUES (713,"Allvarlig");
INSERT INTO nameTable (id,item) VALUES (714,"Lugn");
INSERT INTO nameTable (id,item) VALUES (715,"Ensam");
INSERT INTO nameTable (id,item) VALUES (716,"Blyg");
INSERT INTO nameTable (id,item) VALUES (717,"Lat");
INSERT INTO nameTable (id,item) VALUES (718,"Stygg");
INSERT INTO nameTable (id,item) VALUES (719,"Slughet");
INSERT INTO nameTable (id,item) VALUES (720,"Listig");
INSERT INTO nameTable (id,item) VALUES (721,"Oförskämd");
INSERT INTO nameTable (id,item) VALUES (722,"Självisk");
INSERT INTO nameTable (id,item) VALUES (723,"Envis");
INSERT INTO nameTable (id,item) VALUES (724,"Våldsam(Utåtagerande)");
INSERT INTO nameTable (id,item) VALUES (725,"Materalist");
INSERT INTO nameTable (id,item) VALUES (726,"Girig");
INSERT INTO nameTable (id,item) VALUES (727,"Oärlig");
INSERT INTO nameTable (id,item) VALUES (728,"Grinig");
INSERT INTO nameTable (id,item) VALUES (729,"Deprimerad");
INSERT INTO nameTable (id,item) VALUES (730,"Eländig");
INSERT INTO nameTable (id,item) VALUES (731,"Livet");
INSERT INTO nameTable (id,item) VALUES (732,"Ord");
INSERT INTO nameTable (id,item) VALUES (733,"Meningar");
INSERT INTO nameTable (id,item) VALUES (734,"Skattkammarön");
INSERT INTO nameTable (id,item) VALUES (735,"1.1");
INSERT INTO nameTable (id,item) VALUES (736,"förtiga: tiga om, hemlighålla");
INSERT INTO nameTable (id,item) VALUES (737,"nådens år: kalenderår, herrens år");
INSERT INTO nameTable (id,item) VALUES (738,"linka: halta, stappla");
INSERT INTO nameTable (id,item) VALUES (739,"tjära: ett mörkt tjockflytande ämne som skyddar mot röta (asfalt)");
INSERT INTO nameTable (id,item) VALUES (740,"hårpiska: fläta");
INSERT INTO nameTable (id,item) VALUES (741,"stämma upp: plötsligt börja tala (vid talande)");
INSERT INTO nameTable (id,item) VALUES (742,"gast: 1. spöke 2. besättningsman på segelbåt");
INSERT INTO nameTable (id,item) VALUES (743,"gastkrama: hålla i stark spänning");
INSERT INTO nameTable (id,item) VALUES (744,"ankarspel: mekanisk anordning med vilket ett ankare fälls eller lyfts");
INSERT INTO nameTable (id,item) VALUES (745,"bulta: banka, dunka, slå");
INSERT INTO nameTable (id,item) VALUES (746,"spak: stång, handtag");
INSERT INTO nameTable (id,item) VALUES (747,"brysk: ovänlig, hänsynslös");
INSERT INTO nameTable (id,item) VALUES (748,"kännare: expert, specialist");
INSERT INTO nameTable (id,item) VALUES (749,"bister: hård, sträng(kärv)");
INSERT INTO nameTable (id,item) VALUES (750,"vårdad: ansad, ordentlig, prydlig");
INSERT INTO nameTable (id,item) VALUES (751,"ovårdad: rå, slafskig, raggig, ruggig, rufsig");
INSERT INTO nameTable (id,item) VALUES (752,"matros: sjöman som arbetar på däck");
INSERT INTO nameTable (id,item) VALUES (753,"postdiligens: (används ej idag) coach");
INSERT INTO nameTable (id,item) VALUES (754,"avsides: långt åt sidan, ensligt");
INSERT INTO nameTable (id,item) VALUES (755,"grogg: dryck av sprit blandad med läskedryck");
INSERT INTO nameTable (id,item) VALUES (756,"strövtåg: vandring, upptäcksfärd");
INSERT INTO nameTable (id,item) VALUES (757,"angelägen: ivrig");
INSERT INTO nameTable (id,item) VALUES (758,"ta in på (hotell): hämta in på hotell");
INSERT INTO nameTable (id,item) VALUES (759,"på sätt och vis: i viss mån, på något sätt");
INSERT INTO nameTable (id,item) VALUES (760,"grundval: underbyggnad, grund, basis, fundament");
INSERT INTO nameTable (id,item) VALUES (761,"gestalt: figur, skepnad");
INSERT INTO nameTable (id,item) VALUES (762,"djävul: satan, den onde");
INSERT INTO nameTable (id,item) VALUES (763,"djävulsk: ond, diabolisk, mefistofelisk");
INSERT INTO nameTable (id,item) VALUES (764,"mara: väsen som plågar sovande personer (påhittad)");
INSERT INTO nameTable (id,item) VALUES (765,"utan like: enastående, oerhörd, oförliknelig, unik");
INSERT INTO nameTable (id,item) VALUES (766,"fasa: skräck, fruktan, förfäran, förskräckelse, bäran, ryslighet");
INSERT INTO nameTable (id,item) VALUES (767,"fasansfull: ohygglig, gruvlig, otäck, ruskig");
INSERT INTO nameTable (id,item) VALUES (768,"undgå: låta bli, slippa ifrån");
INSERT INTO nameTable (id,item) VALUES (769,"despot: tyrann, förtyckare, diktator");
INSERT INTO nameTable (id,item) VALUES (770,"despotisk: enväldig, egenmäktig, härsklysten");
INSERT INTO nameTable (id,item) VALUES (771,"rusa upp: rycka till, spritta till, fara upp");
INSERT INTO nameTable (id,item) VALUES (772,"ragla: gå vingligt, stappla, vackla, vingla");
INSERT INTO nameTable (id,item) VALUES (773,"illdåd: brott");
INSERT INTO nameTable (id,item) VALUES (774,"utsago: uttalande");
INSERT INTO nameTable (id,item) VALUES (775,"enligt egen utsago: according to him/her");
INSERT INTO nameTable (id,item) VALUES (776,"tyrann: despot, förtyckare");
INSERT INTO nameTable (id,item) VALUES (777,"tyrranisera: tvinga");
INSERT INTO nameTable (id,item) VALUES (778,"frukta: vara rädd för");
INSERT INTO nameTable (id,item) VALUES (779,"ta mod till sig: våga");
INSERT INTO nameTable (id,item) VALUES (780,"ryta: ge ifrån sig ett kraftigt hotande ljud");
INSERT INTO nameTable (id,item) VALUES (781,"snäsa: tllrättavisa på ett irriterat sätt");
INSERT INTO nameTable (id,item) VALUES (782,"gårdfarihandlare: kringresande försäljare");
INSERT INTO nameTable (id,item) VALUES (783,"brätte: utvikt kant på en hatt");
INSERT INTO nameTable (id,item) VALUES (784,"stuka: vricka, skada");
INSERT INTO nameTable (id,item) VALUES (785,"allmoge: bondebefolkning");
INSERT INTO nameTable (id,item) VALUES (786,"evinnerlig: ständig");
INSERT INTO nameTable (id,item) VALUES (787,"hin håle: hin onde, satan");
INSERT INTO nameTable (id,item) VALUES (788,"reumatism: sjukdomar med smärtor i leder och muskler, ledvärk");
INSERT INTO nameTable (id,item) VALUES (789,"bloss: drag på en cigarett");
INSERT INTO nameTable (id,item) VALUES (790,"sälle: grobian, rackare");
INSERT INTO nameTable (id,item) VALUES (791,"bli kvitt: radera, sudda");
INSERT INTO nameTable (id,item) VALUES (792,"vidrig: förfärlig");
INSERT INTO nameTable (id,item) VALUES (793,"skurk: förbrytare, ligist, usling, bov");
INSERT INTO nameTable (id,item) VALUES (794,"nagla fast: fästa mot");
INSERT INTO nameTable (id,item) VALUES (795,"utspinna sig: äga rum");
INSERT INTO nameTable (id,item) VALUES (796,"tvekamp: duell");
INSERT INTO nameTable (id,item) VALUES (797,"duka under: gå under, ge upp");
INSERT INTO nameTable (id,item) VALUES (798,"ohövligt: ohyfsad, ouppfostrad, fräck");
INSERT INTO nameTable (id,item) VALUES (799,"uppträdande: beteende, uppförande");
INSERT INTO nameTable (id,item) VALUES (800,"sörja för: ta ansvar för");
INSERT INTO nameTable (id,item) VALUES (801,"1.2");
INSERT INTO nameTable (id,item) VALUES (802,"dingla: hänga och svänga");
INSERT INTO nameTable (id,item) VALUES (803,"skört: nedhängande bakstycke av rock");
INSERT INTO nameTable (id,item) VALUES (804,"glåmig: blek som har sjuklig färg");
INSERT INTO nameTable (id,item) VALUES (805,"plira: kisa");
INSERT INTO nameTable (id,item) VALUES (806,"sup: ett glas brännvin");
INSERT INTO nameTable (id,item) VALUES (807,"missta sig: ta fel");
INSERT INTO nameTable (id,item) VALUES (808,"kvickt: snabbt");
INSERT INTO nameTable (id,item) VALUES (809,"tycke: substantiv av tycka, ett åsikt");
INSERT INTO nameTable (id,item) VALUES (810,"inställsam: som fjäskar och smickrar");
INSERT INTO nameTable (id,item) VALUES (811,"välsignelse: blessing");
INSERT INTO nameTable (id,item) VALUES (812,"morsk: orädd, karsk");
INSERT INTO nameTable (id,item) VALUES (813,"kippa efter andan: dra andan häftigt");
INSERT INTO nameTable (id,item) VALUES (814,"stympa: hugga av");
INSERT INTO nameTable (id,item) VALUES (815,"reträtt: flykt");
INSERT INTO nameTable (id,item) VALUES (816,"förefalla: synas, tyckas");
INSERT INTO nameTable (id,item) VALUES (817,"stjälpa: välta");
INSERT INTO nameTable (id,item) VALUES (818,"måtta: sikta, rikta");
INSERT INTO nameTable (id,item) VALUES (819,"jack: hugg, skåra, hack");
INSERT INTO nameTable (id,item) VALUES (820,"befalla: ge order");
INSERT INTO nameTable (id,item) VALUES (821,"blessyr: lättare sår");
INSERT INTO nameTable (id,item) VALUES (822,"lägga benen på ryggen: fly");
INSERT INTO nameTable (id,item) VALUES (823,"krön: högsta punkt (kanske på backe)");
INSERT INTO nameTable (id,item) VALUES (824,"vackla: vara nära att falla");
INSERT INTO nameTable (id,item) VALUES (825,"darrhänt: darrig");
INSERT INTO nameTable (id,item) VALUES (826,"tilldra sig: hända");
INSERT INTO nameTable (id,item) VALUES (827,"banesår: dödande slag");
INSERT INTO nameTable (id,item) VALUES (828,"blotta: göra bar");
INSERT INTO nameTable (id,item) VALUES (829,"flamma: eldslåga");
INSERT INTO nameTable (id,item) VALUES (830,"galge: ställning där dödsdömda hängs");
INSERT INTO nameTable (id,item) VALUES (831,"åder: kanal för blod i kroppen");
INSERT INTO nameTable (id,item) VALUES (832,"för en gångs skull: undantagsvis");
INSERT INTO nameTable (id,item) VALUES (833,"avsäga sig: avstå från, tacka nej");
INSERT INTO nameTable (id,item) VALUES (834,"fästa sig vid: ta fasta på");
INSERT INTO nameTable (id,item) VALUES (835,"1.3");
INSERT INTO nameTable (id,item) VALUES (836,"eftertryck: extra kraftigt understrykande");
INSERT INTO nameTable (id,item) VALUES (837,"kräk: skurk, sälle, lymmmel, fähund");
INSERT INTO nameTable (id,item) VALUES (838,"beck: svart, trögflytande ämne från tjära");
INSERT INTO nameTable (id,item) VALUES (839,"skrov: stomme till ett fartyg");
INSERT INTO nameTable (id,item) VALUES (840,"beveka: röra, övertala, vädja");
INSERT INTO nameTable (id,item) VALUES (841,"skvätt: liten mängd vätska");
INSERT INTO nameTable (id,item) VALUES (842,"vara med om: uppleva, erfara, genomleva");
INSERT INTO nameTable (id,item) VALUES (843,"medtagen: utmattad, sliten");
INSERT INTO nameTable (id,item) VALUES (844,"mutor: gåvor som man ger för att göra någon hjälpa");
INSERT INTO nameTable (id,item) VALUES (845,"stöta: irritera");
INSERT INTO nameTable (id,item) VALUES (846,"koj: sovplats på båt");
INSERT INTO nameTable (id,item) VALUES (847,"roffa: röva");
INSERT INTO nameTable (id,item) VALUES (848,"bjärt: skarp");
INSERT INTO nameTable (id,item) VALUES (849,"yttra: säga");
INSERT INTO nameTable (id,item) VALUES (850,"ta kål på: döda");
INSERT INTO nameTable (id,item) VALUES (851,"dvala: sömn");
INSERT INTO nameTable (id,item) VALUES (852,"bekännelse: medgivande, deklaration");
INSERT INTO nameTable (id,item) VALUES (853,"bestyr: syssla, uppgifter");
INSERT INTO nameTable (id,item) VALUES (854,"lynne: karaktär, humör");
INSERT INTO nameTable (id,item) VALUES (855,"vid: bred");
INSERT INTO nameTable (id,item) VALUES (856,"vanskapt: deformerad, missbildad");
INSERT INTO nameTable (id,item) VALUES (857,"egendom: fastighet på landet");
INSERT INTO nameTable (id,item) VALUES (858,"egendomlig: konstig");
INSERT INTO nameTable (id,item) VALUES (859,"upplysa: informera, förklara");
INSERT INTO nameTable (id,item) VALUES (860,"överrumpla: överraska");
INSERT INTO nameTable (id,item) VALUES (861,"omtöcknad: halvt medvetslös");
INSERT INTO nameTable (id,item) VALUES (862,"klänga: klamra sig fast");
INSERT INTO nameTable (id,item) VALUES (863,"nykter: motsatsord av berusad");
INSERT INTO nameTable (id,item) VALUES (864,"vaja: gunga fram och tillbaka");
INSERT INTO nameTable (id,item) VALUES (865,"stupa: ramla, falla, dö");
INSERT INTO nameTable (id,item) VALUES (866,"strupe: främre delen av halsen");
INSERT INTO nameTable (id,item) VALUES (867,"1.4");
INSERT INTO nameTable (id,item) VALUES (868,"förefalla: synas, tyckas");
INSERT INTO nameTable (id,item) VALUES (869,"annalkande: närmande");
INSERT INTO nameTable (id,item) VALUES (870,"kåre: vindpust (breeze)");
INSERT INTO nameTable (id,item) VALUES (871,"sagt och gjort: färdigt");
INSERT INTO nameTable (id,item) VALUES (872,"tilltagande: ökande, stigande, växande");
INSERT INTO nameTable (id,item) VALUES (873,"skymning: kvällning, halvmörker");
INSERT INTO nameTable (id,item) VALUES (874,"förmodligen: antagligen");
INSERT INTO nameTable (id,item) VALUES (875,"skvalp: plask");
INSERT INTO nameTable (id,item) VALUES (876,"kraxande: som ljud av kråka");
INSERT INTO nameTable (id,item) VALUES (877,"ta till schappen: ta till flykten, fly");
INSERT INTO nameTable (id,item) VALUES (878,"loggert: ett mindre tremastat fartyg");
INSERT INTO nameTable (id,item) VALUES (879,"inge: framkalla, fylla medviss känsla");
INSERT INTO nameTable (id,item) VALUES (880,"harhjärtad: feg, rädd");
INSERT INTO nameTable (id,item) VALUES (881,"rättmätig: laglig, berättigad");
INSERT INTO nameTable (id,item) VALUES (882,"dumdristig: övermodig, obetänksam");
INSERT INTO nameTable (id,item) VALUES (883,"snyfta: gråta med häftiga och stötvisa andetag");
INSERT INTO nameTable (id,item) VALUES (884,"frist: (deadline)");
INSERT INTO nameTable (id,item) VALUES (885,"fingerborg: ett redskap som skyddar fingertopp från stick när nålen sticks genom tyget");
INSERT INTO nameTable (id,item) VALUES (886,"don: redskap, verktyg");
INSERT INTO nameTable (id,item) VALUES (887,"misströsta: ge upp hoppet, tappa modet");
INSERT INTO nameTable (id,item) VALUES (888,"glödga: göra glödhet");
INSERT INTO nameTable (id,item) VALUES (889,"stött: sårad, kränkt");
INSERT INTO nameTable (id,item) VALUES (890,"brokig: färgglad, blandad");
INSERT INTO nameTable (id,item) VALUES (891,"kvadrant: 1/4 cirkel");
INSERT INTO nameTable (id,item) VALUES (892,"tacka: gjutet metallstycke");
INSERT INTO nameTable (id,item) VALUES (893,"ringa: liten, små, obetydlig, otillräcklig");
INSERT INTO nameTable (id,item) VALUES (894,"mässing: legering av koppar och zink");
INSERT INTO nameTable (id,item) VALUES (895,"gruppla: tänka djupt, fundera");
INSERT INTO nameTable (id,item) VALUES (896,"kringflackande: som reser hit och dit");
INSERT INTO nameTable (id,item) VALUES (897,"syndig: elak, ond");
INSERT INTO nameTable (id,item) VALUES (898,"ta i: känna, feel");
INSERT INTO nameTable (id,item) VALUES (899,"klinga: ringa, ljuda, tona");
INSERT INTO nameTable (id,item) VALUES (900,"styver: öre, slant, mynt");
INSERT INTO nameTable (id,item) VALUES (901,"tidsödande: som tar lång tid");
INSERT INTO nameTable (id,item) VALUES (902,"regel: används i en stomme för väggen");
INSERT INTO nameTable (id,item) VALUES (903,"regla: låsa, stänga med dörr och vägganordning");
INSERT INTO nameTable (id,item) VALUES (904,"svärm: grupp av flygande djur");
INSERT INTO nameTable (id,item) VALUES (905,"treva: fumla, osäkert leta reda på");
INSERT INTO nameTable (id,item) VALUES (906,"kulle: rundad höjd");
INSERT INTO nameTable (id,item) VALUES (907,"sänka: dal, dalgång");
INSERT INTO nameTable (id,item) VALUES (908,"klandra: kritisera, anklaga, beskylla");
INSERT INTO nameTable (id,item) VALUES (909,"stappla: gå ostadigt och snubblande, vackla");
INSERT INTO nameTable (id,item) VALUES (910,"hårdhänt: sträng, hård, med järnhand");
INSERT INTO nameTable (id,item) VALUES (911,"1.5");
INSERT INTO nameTable (id,item) VALUES (912,"uppehåll: avbrott, oaus");
INSERT INTO nameTable (id,item) VALUES (913,"ryslig: förskräcklig, otäck");
INSERT INTO nameTable (id,item) VALUES (914,"söla: vara långsam, dröja");
INSERT INTO nameTable (id,item) VALUES (915,"sölkorv: person som är långsam och dröjer");
INSERT INTO nameTable (id,item) VALUES (916,"klösa: riva med klor eller naglar");
INSERT INTO nameTable (id,item) VALUES (917,"snoka: rota i andras bostad, gräva");
INSERT INTO nameTable (id,item) VALUES (918,"sluttning: lutande markområde");
INSERT INTO nameTable (id,item) VALUES (919,"fähund: kräk, elak och usel person");
INSERT INTO nameTable (id,item) VALUES (920,"vädjan: bön, uppmaning, upprop");
INSERT INTO nameTable (id,item) VALUES (921,"fena: simorgan hos fisk");
INSERT INTO nameTable (id,item) VALUES (922,"röra inte en fena: helt stilla");
INSERT INTO nameTable (id,item) VALUES (923,"snylta: tigga");
INSERT INTO nameTable (id,item) VALUES (924,"ruter: kraft, energi");
INSERT INTO nameTable (id,item) VALUES (925,"gasta: skrika, vråla");
INSERT INTO nameTable (id,item) VALUES (926,"invända: säga emot");
INSERT INTO nameTable (id,item) VALUES (927,"ta överhand: bli dominerande");
INSERT INTO nameTable (id,item) VALUES (928,"förgäves: utan resultat");
INSERT INTO nameTable (id,item) VALUES (929,"utefter: längs med");
INSERT INTO nameTable (id,item) VALUES (930,"ryttare: person som rider");
INSERT INTO nameTable (id,item) VALUES (931,"väja: vika undan, undvika");
INSERT INTO nameTable (id,item) VALUES (932,"yngling: pojke, ung man");
INSERT INTO nameTable (id,item) VALUES (933,"omständighet: förhållande");
INSERT INTO nameTable (id,item) VALUES (934,"luktsalt: används att väcka medvetslösa personer");
INSERT INTO nameTable (id,item) VALUES (935,"bakhåll: anfall från ett gömställe");
INSERT INTO nameTable (id,item) VALUES (936,"udde: liten halvö");
INSERT INTO nameTable (id,item) VALUES (937,"kutter: snabbsegelbåt");
INSERT INTO nameTable (id,item) VALUES (938,"liktorn: förtjockning av överhuden (kanske på tårna)");
INSERT INTO nameTable (id,item) VALUES (939,"penning: mynt, pengar");
INSERT INTO nameTable (id,item) VALUES (940,"krita: vit och mjuk kalksten");
INSERT INTO nameTable (id,item) VALUES (941,"när det kommer till kritan: när det verkligen gäller");
INSERT INTO nameTable (id,item) VALUES (942,"majestät: höghet");
INSERT INTO nameTable (id,item) VALUES (943,"rask: snabb, fort");
INSERT INTO nameTable (id,item) VALUES (944,"trampa på tårna: behandla nedsättande");
INSERT INTO nameTable (id,item) VALUES (945,"1.6");
INSERT INTO nameTable (id,item) VALUES (946,"avlövad: utan löv, bar");
INSERT INTO nameTable (id,item) VALUES (947,"betjänt: manservant, uppassare");
INSERT INTO nameTable (id,item) VALUES (948,"belägga: täcka");
INSERT INTO nameTable (id,item) VALUES (949,"byst: skulptur på bröstbild");
INSERT INTO nameTable (id,item) VALUES (950,"brasa: eld");
INSERT INTO nameTable (id,item) VALUES (951,"munter: synbart glad och obekymrad");
INSERT INTO nameTable (id,item) VALUES (952,"väderbiten: som fått färg av väder och vind");
INSERT INTO nameTable (id,item) VALUES (953,"garva: färgar hudar till läder");
INSERT INTO nameTable (id,item) VALUES (954,"garvard: härdad (experienced)");
INSERT INTO nameTable (id,item) VALUES (955,"fåra: rynka, ränna");
INSERT INTO nameTable (id,item) VALUES (956,"tyda på: ge skäl att tro, peka mot");
INSERT INTO nameTable (id,item) VALUES (957,"givakt: formalposition som soldat");
INSERT INTO nameTable (id,item) VALUES (958,"Vilka vindar för er hit: en mening då man besvarar när någon kommer oväntat");
INSERT INTO nameTable (id,item) VALUES (959,"spiselkrans: dekorativ ramen runt öppen spis");
INSERT INTO nameTable (id,item) VALUES (960,"snagga: klippa mycket kort");
INSERT INTO nameTable (id,item) VALUES (961,"vedervärdig: avskyvärd, äcklig, vidrig");
INSERT INTO nameTable (id,item) VALUES (962,"förtjänst: god egenskap");
INSERT INTO nameTable (id,item) VALUES (963,"det kliar i fingarna på honom att: han har väldig lust att genast göra");
INSERT INTO nameTable (id,item) VALUES (964,"förtjänt: värd");
INSERT INTO nameTable (id,item) VALUES (965,"stygn: (stitch)");
INSERT INTO nameTable (id,item) VALUES (966,"försegla: tillsluta med sigill, seal");
INSERT INTO nameTable (id,item) VALUES (967,"kråkfötter: klotter");
INSERT INTO nameTable (id,item) VALUES (968,"införa: börjar använda, tillämpa");
INSERT INTO nameTable (id,item) VALUES (969,"förväxling: sammanblandning");
INSERT INTO nameTable (id,item) VALUES (970,"förtydligande: klarläggande tillägg");
INSERT INTO nameTable (id,item) VALUES (971,"kapa: erövra under vapenhot (hijack)");
INSERT INTO nameTable (id,item) VALUES (972,"berest: som har rest mest");
INSERT INTO nameTable (id,item) VALUES (973,"sigill: avtryck i lack vid försegling");
INSERT INTO nameTable (id,item) VALUES (974,"varsam: försiktig, aktsam");
INSERT INTO nameTable (id,item) VALUES (975,"lodning: mätning av vattendjup");
INSERT INTO nameTable (id,item) VALUES (976,"sund: smalt vattenområde mellan två landsområden");
INSERT INTO nameTable (id,item) VALUES (977,"inlopp: infartsled till hamn (entrance)");
INSERT INTO nameTable (id,item) VALUES (978,"mässpojke: pojke som är servitör i fartygsmatsal");
INSERT INTO nameTable (id,item) VALUES (979,"gynnsam: lyckosam");
INSERT INTO nameTable (id,item) VALUES (980,"skonert: segelfartyg");
INSERT INTO nameTable (id,item) VALUES (981,"2.1 Jag reser till Bristol");
INSERT INTO nameTable (id,item) VALUES (982,"hushållerska: vaktmästare");
INSERT INTO nameTable (id,item) VALUES (983,"omväxlande: varierande");
INSERT INTO nameTable (id,item) VALUES (984,"vilde: person som är född och lever i primitiv kultur");
INSERT INTO nameTable (id,item) VALUES (985,"knyffel: skojig benämning på pojke");
INSERT INTO nameTable (id,item) VALUES (986,"få nys om: höra talas om");
INSERT INTO nameTable (id,item) VALUES (987,"spottstyver: liten summa av pengar");
INSERT INTO nameTable (id,item) VALUES (988,"synnerligen: mycket, i högsta grad");
INSERT INTO nameTable (id,item) VALUES (989,"avog: fientlig, avvisande");
INSERT INTO nameTable (id,item) VALUES (990,"oförskämd: fräck och oartig, shameless");
INSERT INTO nameTable (id,item) VALUES (991,"rena rama: ingenting mindre än");
INSERT INTO nameTable (id,item) VALUES (992,"förtal: lögnaktigt skvaller");
INSERT INTO nameTable (id,item) VALUES (993,"bestrida: förneka");
INSERT INTO nameTable (id,item) VALUES (994,"retfull: förarglig");
INSERT INTO nameTable (id,item) VALUES (995,"rigga: montera, sätta upp, göra i ordning");
INSERT INTO nameTable (id,item) VALUES (996,"inföding: person som är infödd här, native");
INSERT INTO nameTable (id,item) VALUES (997,"fördömd: förbaskad");
INSERT INTO nameTable (id,item) VALUES (998,"kolossal: jättestor, enorm");
INSERT INTO nameTable (id,item) VALUES (999,"medlidande: medkänsla, empati, sympati");
INSERT INTO nameTable (id,item) VALUES (1000,"fregatt: krigsskepp, eskortfartyg");
INSERT INTO nameTable (id,item) VALUES (1001,"tjusning: charm, fascination, förtrollning");
INSERT INTO nameTable (id,item) VALUES (1002,"förvrida: deformera, vanställa, göra tokig");
INSERT INTO nameTable (id,item) VALUES (1003,"omgående: genast");
INSERT INTO nameTable (id,item) VALUES (1004,"aktning: respekt");
INSERT INTO nameTable (id,item) VALUES (1005,"örlogsfartyg: fregatt, krigskepp");
INSERT INTO nameTable (id,item) VALUES (1006,"välbärgad: ganska rik");
INSERT INTO nameTable (id,item) VALUES (1007,"överskrida: gå över en gräns");
INSERT INTO nameTable (id,item) VALUES (1008,"fruntimmer: nedsättande ord för kvinna");
INSERT INTO nameTable (id,item) VALUES (1009,"färgad: som inte tillhör vit ras");
INSERT INTO nameTable (id,item) VALUES (1010,"förhandling: disussion för att nå en överenskommelse");
INSERT INTO nameTable (id,item) VALUES (1011,"gångspel: ankarspel");
INSERT INTO nameTable (id,item) VALUES (1012,"bege sig: gå fara, resa");
INSERT INTO nameTable (id,item) VALUES (1013,"vålla: framkalla, orsaka");
INSERT INTO nameTable (id,item) VALUES (1014,"karm: ram runt fönster eller dörr");
INSERT INTO nameTable (id,item) VALUES (1015,"karmstol: fåtölj, stol med armstöd");
INSERT INTO nameTable (id,item) VALUES (1016,"ställa till besvär: trassla, make a mess, play up");
INSERT INTO nameTable (id,item) VALUES (1017,"göra livet surt för: trakassera, mobba");
INSERT INTO nameTable (id,item) VALUES (1018,"tillrättavisa: förebrå, lägga skulden på");
INSERT INTO nameTable (id,item) VALUES (1019,"trycka ner i skorna: mobba");
INSERT INTO nameTable (id,item) VALUES (1020,"ta avsked av: säga hejdå till");
INSERT INTO nameTable (id,item) VALUES (1021,"hed: trädlös slättmark");
INSERT INTO nameTable (id,item) VALUES (1022,"rigg: anordning för att föra segel på en båt");
INSERT INTO nameTable (id,item) VALUES (1023,"galjonsbild: en allegorisk bild snidad i trä, föreställer vanligen en figur relaterad till fartygs namn eller en kvinnogestalt");
INSERT INTO nameTable (id,item) VALUES (1024,"polisong: kindskägg");
INSERT INTO nameTable (id,item) VALUES (1025,"svajig: vinglig, instabil");
INSERT INTO nameTable (id,item) VALUES (1026,"manskap: besättning, trupp, arbetslag");
INSERT INTO nameTable (id,item) VALUES (1027,"fulltaglig: komplett, som har fullt antal");
INSERT INTO nameTable (id,item) VALUES (1028,"vanka: gå långsamt");
INSERT INTO nameTable (id,item) VALUES (1029,"2.2 På värdshuset kikaren");
INSERT INTO nameTable (id,item) VALUES (1030,"vimmel: stor oordnad mängd");
INSERT INTO nameTable (id,item) VALUES (1031,"vimlet av folk: mycket folk");
INSERT INTO nameTable (id,item) VALUES (1032,"bal: förpackning");
INSERT INTO nameTable (id,item) VALUES (1033,"bråd: busy, sudden");
INSERT INTO nameTable (id,item) VALUES (1034,"vid första anblick: at first sight");
INSERT INTO nameTable (id,item) VALUES (1035,"alldaglig: vanlig");
INSERT INTO nameTable (id,item) VALUES (1036,"blekfet: tjock, svullen, överviktig");
INSERT INTO nameTable (id,item) VALUES (1037,"inte ett dyft; inte alls");
INSERT INTO nameTable (id,item) VALUES (1038,"mahogny: ett röd/mörkbrun ädelträ");
INSERT INTO nameTable (id,item) VALUES (1039,"slokörad: som skäms, skamsen");
INSERT INTO nameTable (id,item) VALUES (1040,"tuggbuss: en mindre bit tuggtobak");
INSERT INTO nameTable (id,item) VALUES (1041,"köl: båts understa del");
INSERT INTO nameTable (id,item) VALUES (1042,"hala: dra");
INSERT INTO nameTable (id,item) VALUES (1043,"kölhalning: bestraffningsform att dra under fartygs köl");
INSERT INTO nameTable (id,item) VALUES (1044,"slå sig i backen på: vara övertygad om");
INSERT INTO nameTable (id,item) VALUES (1045,"slöfock: slö person, latmask");
INSERT INTO nameTable (id,item) VALUES (1046,"slipad: listig, slug");
INSERT INTO nameTable (id,item) VALUES (1047,"gå i god för: garantera, ansvara, intyga");
INSERT INTO nameTable (id,item) VALUES (1048,"tappa hakan: bli ställd, gapa av förvåning");
INSERT INTO nameTable (id,item) VALUES (1049,"följeslagare: sällskap");
INSERT INTO nameTable (id,item) VALUES (1050,"tonnage: fartygs lastningsförmåga");
INSERT INTO nameTable (id,item) VALUES (1051,"lossa: lasta av");
INSERT INTO nameTable (id,item) VALUES (1052,"hysa: ge plats åt, ha, känna");
INSERT INTO nameTable (id,item) VALUES (1053,"förtjusning: glädje");
INSERT INTO nameTable (id,item) VALUES (1054,"förtrolig: confidence");
INSERT INTO nameTable (id,item) VALUES (1055,"farstu: förstuga, tambur");
INSERT INTO nameTable (id,item) VALUES (1056,"2.3 Krut och vapen");
INSERT INTO nameTable (id,item) VALUES (1057,"redd: ankringsplats utanför hamn");
INSERT INTO nameTable (id,item) VALUES (1058,"akter: bakre del på en båt");
INSERT INTO nameTable (id,item) VALUES (1059,"tross: grovt rep");
INSERT INTO nameTable (id,item) VALUES (1060,"vindögd: som tittar i korst, skelögd");
INSERT INTO nameTable (id,item) VALUES (1061,"komma underfund med: fatta");
INSERT INTO nameTable (id,item) VALUES (1062,"uppriktig: ärlig, rak, frank");
INSERT INTO nameTable (id,item) VALUES (1063,"seglats: segeltur, sjöresa");
INSERT INTO nameTable (id,item) VALUES (1064,"farkost: fortskaffningsmedel i vatten eller luft");
INSERT INTO nameTable (id,item) VALUES (1065,"sämja: vänskap, samförstång, harmoni");
INSERT INTO nameTable (id,item) VALUES (1066,"för om masten: där manskap befinner sig");
INSERT INTO nameTable (id,item) VALUES (1067,"rådfråga: konsultera, be om råd");
INSERT INTO nameTable (id,item) VALUES (1068,"försummelse: underlåtenhet, vårdslöshet (neglect)");
INSERT INTO nameTable (id,item) VALUES (1069,"stuva: packa, lasta omsorgsfullt i ett lastutrymme");
INSERT INTO nameTable (id,item) VALUES (1070,"kajuta: rum i aktern, chefens rum på örlogsfartyg");
INSERT INTO nameTable (id,item) VALUES (1071,"skans: manskapsrum");
INSERT INTO nameTable (id,item) VALUES (1072,"avseende: hänsyn, attention");
INSERT INTO nameTable (id,item) VALUES (1073,"fästa avseende vid: lägga vikt vid");
INSERT INTO nameTable (id,item) VALUES (1074,"anhålla: be, begära");
INSERT INTO nameTable (id,item) VALUES (1075,"garnison: militärförläggning");
INSERT INTO nameTable (id,item) VALUES (1076,"myteri: uppror, vägran att lyda order");
INSERT INTO nameTable (id,item) VALUES (1077,"förolämpa: såra, kränka, insultera, offend");
INSERT INTO nameTable (id,item) VALUES (1078,"bestrida: förneka, opponera sig emot");
INSERT INTO nameTable (id,item) VALUES (1079,"lägga ord i min mun: uttryck för jag har aldrig sagt det");
INSERT INTO nameTable (id,item) VALUES (1080,"ombordvarande: personer ombord");
INSERT INTO nameTable (id,item) VALUES (1081,"befattning: tjänst, arbete, positiion");
INSERT INTO nameTable (id,item) VALUES (1082,"intim: som är i nära kontakt");
INSERT INTO nameTable (id,item) VALUES (1083,"supa: dricka mycket sprit");
INSERT INTO nameTable (id,item) VALUES (1084,"fabel: djursaga");
INSERT INTO nameTable (id,item) VALUES (1085,"klipsk: klok, klartänkt, snabbtänkt");
INSERT INTO nameTable (id,item) VALUES (1086,"dra åt skogen: dra åt helvete");
INSERT INTO nameTable (id,item) VALUES (1087,"falla sig: råka vara, råka bli, inträffa");
INSERT INTO nameTable (id,item) VALUES (1088,"avlägsna: få att försvinna, ta bort");
INSERT INTO nameTable (id,item) VALUES (1089,"avlägsna sig: lämna");
INSERT INTO nameTable (id,item) VALUES (1090,"farhåga: fruktan, ängslan");
INSERT INTO nameTable (id,item) VALUES (1091,"humbug: bluffmakare, svindlare");
INSERT INTO nameTable (id,item) VALUES (1092,"föga: väldigt lite");
INSERT INTO nameTable (id,item) VALUES (1093,"värdig: allvarlig, högtidlig, passande");
INSERT INTO nameTable (id,item) VALUES (1094,"kabyss: skeppskök");
INSERT INTO nameTable (id,item) VALUES (1095,"babord: vänster sida på en båt sett från aktern");
INSERT INTO nameTable (id,item) VALUES (1096,"kapp: överbyggnad över luckor och nedgångar på fartygsdäck");
INSERT INTO nameTable (id,item) VALUES (1097,"utvidga: expandera, utöka");
INSERT INTO nameTable (id,item) VALUES (1098,"vig: rörlig, smidig, spänstig");
INSERT INTO nameTable (id,item) VALUES (1099,"honnör: militär hälsning");
INSERT INTO nameTable (id,item) VALUES (1100,"mässingpjäs: tyngre eldvapen av legering av koppar och zink");
INSERT INTO nameTable (id,item) VALUES (1101,"gullgösse: kelgris, bortskämt barn");
INSERT INTO nameTable (id,item) VALUES (1102,"2.4 Resan");
INSERT INTO nameTable (id,item) VALUES (1103,"gryning: tidig morgon när det börjar ljusning");
INSERT INTO nameTable (id,item) VALUES (1104,"lanterna: ljus som lyser på fartyg eller flygplan");
INSERT INTO nameTable (id,item) VALUES (1105,"stämma upp en sång: intonera, börja sjunga, ange tonen");
INSERT INTO nameTable (id,item) VALUES (1106,"stekvändaren: stekkcok");
INSERT INTO nameTable (id,item) VALUES (1107,"redogöra för: berätta om");
INSERT INTO nameTable (id,item) VALUES (1108,"i höjd med: jäms med (at the same height)");
INSERT INTO nameTable (id,item) VALUES (1109,"kommendera: beordra");
INSERT INTO nameTable (id,item) VALUES (1110,"krypin: litet rum, vrå");
INSERT INTO nameTable (id,item) VALUES (1111,"gåta: mysterium, hemlighet");
INSERT INTO nameTable (id,item) VALUES (1112,"slå någon i järn: låsa fast någon");
INSERT INTO nameTable (id,item) VALUES (1113,"befordra: förflytta till högre tjänst");
INSERT INTO nameTable (id,item) VALUES (1114,"slup: loggert");
INSERT INTO nameTable (id,item) VALUES (1115,"anförtro: delegera, lämna med förtroende");
INSERT INTO nameTable (id,item) VALUES (1116,"kila fast: sätta fast/fixera med en kil");
INSERT INTO nameTable (id,item) VALUES (1117,"skott: skiljevägg");
INSERT INTO nameTable (id,item) VALUES (1118,"invalidisera: handikappa, disable");
INSERT INTO nameTable (id,item) VALUES (1119,"rorgängare: styrman");
INSERT INTO nameTable (id,item) VALUES (1120,"hugga tag i: hantera, tackle");
INSERT INTO nameTable (id,item) VALUES (1121,"fröjd: stor glädje");
INSERT INTO nameTable (id,item) VALUES (1122,"borda: lägga till vid och klättra ett annat fartyg");
INSERT INTO nameTable (id,item) VALUES (1123,"osa: stinka, lukta, sprida os");
INSERT INTO nameTable (id,item) VALUES (1124,"pannlugg: hår på framme (panna)");
INSERT INTO nameTable (id,item) VALUES (1125,"sluddra: prata otydligt");
INSERT INTO nameTable (id,item) VALUES (1126,"spänne: (buckle)");
INSERT INTO nameTable (id,item) VALUES (1127,"barsk: sträng, bister");
INSERT INTO nameTable (id,item) VALUES (1128,"sätta näsan i vädret: ett uttryck för att vara för stolt");
INSERT INTO nameTable (id,item) VALUES (1129,"lätta ankar: börja en sjöresa, avsegla");
INSERT INTO nameTable (id,item) VALUES (1130,"ranson: tilldelning, andel, portion");
INSERT INTO nameTable (id,item) VALUES (1131,"i lovart: det håll från vilket vinden blåser");
INSERT INTO nameTable (id,item) VALUES (1132,"i lä: det motsatta håll från vilket vinden blåser");
INSERT INTO nameTable (id,item) VALUES (1133,"kurs: fartygsriktning");
INSERT INTO nameTable (id,item) VALUES (1134,"bogspröt: rundhult som sticker ut framåt från ett fartyg");
INSERT INTO nameTable (id,item) VALUES (1135,"yra: virvla runt i luften");
INSERT INTO nameTable (id,item) VALUES (1136,"klut: segel");
INSERT INTO nameTable (id,item) VALUES (1137,"sätta till alla klutar: uttryck för att anstränga sig, uppbjuda all krafter");
INSERT INTO nameTable (id,item) VALUES (1138,"roder: styranordning på en båt");
INSERT INTO nameTable (id,item) VALUES (1139,"bog: främsta delen på en båt");
INSERT INTO nameTable (id,item) VALUES (1140,"sorl: brus");
INSERT INTO nameTable (id,item) VALUES (1141,"medge: ersänna");
INSERT INTO nameTable (id,item) VALUES (1142,"2.5 Vad jag hörde i äppeltunnan");
INSERT INTO nameTable (id,item) VALUES (1143,"bredsida: bombanfall, skottlossning, avfyrning av kanoner");
INSERT INTO nameTable (id,item) VALUES (1144,"välbehållen: oskadad, hel");
INSERT INTO nameTable (id,item) VALUES (1145,"nedsölad: smutsig");
INSERT INTO nameTable (id,item) VALUES (1146,"lägga undan: spara");
INSERT INTO nameTable (id,item) VALUES (1147,"matros: sjöman");
INSERT INTO nameTable (id,item) VALUES (1148,"emmellertid: however, ändå, i alla fall");
INSERT INTO nameTable (id,item) VALUES (1149,"furste: höving, person som regerar en stat");
INSERT INTO nameTable (id,item) VALUES (1150,"sorglös: bekymmersfri, obetänksam");
INSERT INTO nameTable (id,item) VALUES (1151,"inventarier; lös egendom i ett hus");
INSERT INTO nameTable (id,item) VALUES (1152,"korrumpera: muta, fördärva");
INSERT INTO nameTable (id,item) VALUES (1153,"prima: förstaklassig");
INSERT INTO nameTable (id,item) VALUES (1154,"dumbom: dum person");
INSERT INTO nameTable (id,item) VALUES (1155,"hunsa: mobba");
INSERT INTO nameTable (id,item) VALUES (1156,"amputera: operera bort till exempel ett ben vid skada");
INSERT INTO nameTable (id,item) VALUES (1157,"skuta: mindre fartyg");
INSERT INTO nameTable (id,item) VALUES (1158,"gå bet på: förlora spelet, misslyckas, inte klara av något");
INSERT INTO nameTable (id,item) VALUES (1159,"galgbacke: galgberg");
INSERT INTO nameTable (id,item) VALUES (1160,"kupp: överraskande handling för att ta makten");
INSERT INTO nameTable (id,item) VALUES (1161,"på kuppen: på grund därav, som resultat");
INSERT INTO nameTable (id,item) VALUES (1162,"predika: tala i en kyrka, förkunna, uttala sin mening offentligt");
INSERT INTO nameTable (id,item) VALUES (1163,"hårding: tuff kille");
INSERT INTO nameTable (id,item) VALUES (1164,"kverulant: person som gnäller och klagar");
INSERT INTO nameTable (id,item) VALUES (1165,"ombedas: passiv, bli hövligt uppmanad");
INSERT INTO nameTable (id,item) VALUES (1166,"omgång: runda, parti");
INSERT INTO nameTable (id,item) VALUES (1167,"kagge: balja, liten tunna");
INSERT INTO nameTable (id,item) VALUES (1168,"lösryckt: ensam, ofullständig");
INSERT INTO nameTable (id,item) VALUES (1169,"skalda: dikta");
INSERT INTO nameTable (id,item) VALUES (1170,"huld: tillgiven, ljuv, gynnsam");
INSERT INTO nameTable (id,item) VALUES (1171,"försilvra: överdra med silver");
INSERT INTO nameTable (id,item) VALUES (1172,"förgylla: överdra med guld");
INSERT INTO nameTable (id,item) VALUES (1173,"mesan: den aktersta masten på segelfartyg");
INSERT INTO nameTable (id,item) VALUES (1174,"fock: segel");
INSERT INTO nameTable (id,item) VALUES (1175,"2.6 Krigsråd");
INSERT INTO nameTable (id,item) VALUES (1176,"krigsråd: (war council)");
INSERT INTO nameTable (id,item) VALUES (1177,"bog: främste delen på en båt");
INSERT INTO nameTable (id,item) VALUES (1178,"kägla: koniskt trästycke som ska slås omkull i vissa spel till exempel bowling");
INSERT INTO nameTable (id,item) VALUES (1179,"brassa: vrida segeln och rår med vind");
INSERT INTO nameTable (id,item) VALUES (1180,"brassa på: satsa för fullt");
INSERT INTO nameTable (id,item) VALUES (1181,"holme: liten ö");
INSERT INTO nameTable (id,item) VALUES (1182,"tillhåll: gömställe");
INSERT INTO nameTable (id,item) VALUES (1183,"dreja: 1. minska ett segelfartygs fart till minsta, 2. forma lergods på roterade skiva");
INSERT INTO nameTable (id,item) VALUES (1184,"farvatten: vattenväg (hav)");
INSERT INTO nameTable (id,item) VALUES (1185,"förevändning: skäl, ursäkt, excuse");
INSERT INTO nameTable (id,item) VALUES (1186,"skifta: byta, växla");
INSERT INTO nameTable (id,item) VALUES (1187,"frikostig: generös");
INSERT INTO nameTable (id,item) VALUES (1188,"till väders: i höjden, uppåt, mot skyn");
INSERT INTO nameTable (id,item) VALUES (1189,"bolma: röka, ryka kraftigt");
INSERT INTO nameTable (id,item) VALUES (1190,"kölvatten: svallvåg");
INSERT INTO nameTable (id,item) VALUES (1191,"avvakta: vänta på");
INSERT INTO nameTable (id,item) VALUES (1192,"mått och steg: åtgärd, disposition");
INSERT INTO nameTable (id,item) VALUES (1193,"rånock; spets på en skogsbacke, trästycke");
INSERT INTO nameTable (id,item) VALUES (1194,"storsint: generös, tolerant");
INSERT INTO nameTable (id,item) VALUES (1195,"sammanstötning: kollision, strid, konflikt");
INSERT INTO nameTable (id,item) VALUES (1196,"påfrestande: besvärlig, ansträngande, slitig");
INSERT INTO nameTable (id,item) VALUES (1197,"vaken: uppmärksam (alert)");
INSERT INTO nameTable (id,item) VALUES (1198,"3.1 Hur mitt äventyr i land började");
INSERT INTO nameTable (id,item) VALUES (1199,"mojna: bli stilla");
INSERT INTO nameTable (id,item) VALUES (1200,"stiltje: vindstilla, calm");
INSERT INTO nameTable (id,item) VALUES (1201,"gråaktig: färglös, blek, matt, grå");
INSERT INTO nameTable (id,item) VALUES (1202,"sandrevel: sandrev, sandås, sandbank");
INSERT INTO nameTable (id,item) VALUES (1203,"vegetation: växtlighet");
INSERT INTO nameTable (id,item) VALUES (1204,"spira: smal rund stav, pole");
INSERT INTO nameTable (id,item) VALUES (1205,"sockel: underlag, fundament, base");
INSERT INTO nameTable (id,item) VALUES (1206,"dyning: sjöhävning, havsvågor som vandrat från det vindområde där de bildats");
INSERT INTO nameTable (id,item) VALUES (1207,"guppa: gunga på vattenytan");
INSERT INTO nameTable (id,item) VALUES (1208,"fastande mage: tom mage");
INSERT INTO nameTable (id,item) VALUES (1209,"i synnerhet: särskilt");
INSERT INTO nameTable (id,item) VALUES (1210,"melankoli: dyster, djup nedstämdhet");
INSERT INTO nameTable (id,item) VALUES (1211,"bränning: våg som bryts mot strand");
INSERT INTO nameTable (id,item) VALUES (1212,"envar: var och en, alla");
INSERT INTO nameTable (id,item) VALUES (1213,"blotta: bara, avslöja");
INSERT INTO nameTable (id,item) VALUES (1214,"tillstymmelse: (i nekande uttryck) aning, antydan");
INSERT INTO nameTable (id,item) VALUES (1215,"bogsera: dra släpa");
INSERT INTO nameTable (id,item) VALUES (1216,"knota: klaga lågmält, gnälla");
INSERT INTO nameTable (id,item) VALUES (1217,"föra befäl: be in command, bli officer");
INSERT INTO nameTable (id,item) VALUES (1218,"åsyn: syn, anblick");
INSERT INTO nameTable (id,item) VALUES (1219,"rorsman: styrman, förare");
INSERT INTO nameTable (id,item) VALUES (1220,"lotsa: styra fartyg genom besvärliga farvatten");
INSERT INTO nameTable (id,item) VALUES (1222,"plumsa: plaska, falla tungt ner i vatten");
INSERT INTO nameTable (id,item) VALUES (1223,"amfiteater: utomhus scen (teater)");
INSERT INTO nameTable (id,item) VALUES (1224,"kärr: träsk, myr, sumpmark");
INSERT INTO nameTable (id,item) VALUES (1225,"kvalmig: kvav, varm och svår att andas");
INSERT INTO nameTable (id,item) VALUES (1226,"våga: sätta på spel, satsa, riskera");
INSERT INTO nameTable (id,item) VALUES (1227,"föredöme: förebild, exempel");
INSERT INTO nameTable (id,item) VALUES (1228,"formligen: alldeles, helt, bokstavligen, absolut");
INSERT INTO nameTable (id,item) VALUES (1229,"överträffa: vara bättre än");
INSERT INTO nameTable (id,item) VALUES (1230,"tillmötesgående: hjälpsam, tjänstvillig");
INSERT INTO nameTable (id,item) VALUES (1231,"idel: bara, helt och hållet, ren, nothing but");
INSERT INTO nameTable (id,item) VALUES (1232,"lyster: glans");
INSERT INTO nameTable (id,item) VALUES (1233,"pik: elakt ord, spydighet, illvilighet");
INSERT INTO nameTable (id,item) VALUES (1234,"vina: ge ifrån sig ett högt och gällt och ihållande ljud");
INSERT INTO nameTable (id,item) VALUES (1235,"tala förstånd med: 1. ta itu med, 2. förklara för någon (reason with someone)");
INSERT INTO nameTable (id,item) VALUES (1236,"sanna mina ord: det kommer att bli som jag har sagt");
INSERT INTO nameTable (id,item) VALUES (1237,"inviga: göra någon förtrogen");
INSERT INTO nameTable (id,item) VALUES (1238,"snava: snubbla, stöta foten mot något och tappa balansen");
INSERT INTO nameTable (id,item) VALUES (1239,"maska: söla, förhala tiden, mjölka");
INSERT INTO nameTable (id,item) VALUES (1240,"besittning: innehav, ägande");
INSERT INTO nameTable (id,item) VALUES (1241,"ta i bisittning: occupy, dominate");
INSERT INTO nameTable (id,item) VALUES (1242,"infall: (plötslig) idé, uppslag, nyck");
INSERT INTO nameTable (id,item) VALUES (1243,"bemäktiga sig: kapa, ta i besittning, erövra");
INSERT INTO nameTable (id,item) VALUES (1244,"reling: räcke, övre kant på en båtsida");
INSERT INTO nameTable (id,item) VALUES (1245,"åra: redskap att ro med, oar");
INSERT INTO nameTable (id,item) VALUES (1246,"snår: risig småskog, buskage");
INSERT INTO nameTable (id,item) VALUES (1247,"gå dit näsan pekar: uttryck för att gå utan att tänka sig för, utan mål");
INSERT INTO nameTable (id,item) VALUES (1248,"i kapp: i tävling");
INSERT INTO nameTable (id,item) VALUES (1249,"försprång: ledning, ledande ställning, försteg");
INSERT INTO nameTable (id,item) VALUES (1250,"3.2 Den första striden");
INSERT INTO nameTable (id,item) VALUES (1251,"sumpmark: träsk, myr, kärr, sankmark");
INSERT INTO nameTable (id,item) VALUES (1252,"bevuxen: täckt, beklädd med");
INSERT INTO nameTable (id,item) VALUES (1253,"föga: väldigt lite");
INSERT INTO nameTable (id,item) VALUES (1254,"dunge: liten samling träd");
INSERT INTO nameTable (id,item) VALUES (1255,"törn: tagg");
INSERT INTO nameTable (id,item) VALUES (1256,"kontur: ytterlinje");
INSERT INTO nameTable (id,item) VALUES (1257,"dis: lätt dimma");
INSERT INTO nameTable (id,item) VALUES (1258,"soldis: solrök");
INSERT INTO nameTable (id,item) VALUES (1259,"snattra: låta som ankor, kackel");
INSERT INTO nameTable (id,item) VALUES (1260,"fastställa: bestämma, besluta");
INSERT INTO nameTable (id,item) VALUES (1261,"inkräktare: person som tar sig in objuden");
INSERT INTO nameTable (id,item) VALUES (1262,"gassa: bränna, steka");
INSERT INTO nameTable (id,item) VALUES (1263,"fyllig: som har stort omfång, mullig");
INSERT INTO nameTable (id,item) VALUES (1264,"beveka: få någon att ändra inställning genom känsloargument, vädja");
INSERT INTO nameTable (id,item) VALUES (1265,"korp: kråkfågel");
INSERT INTO nameTable (id,item) VALUES (1266,"inbilla: få någon att tro");
INSERT INTO nameTable (id,item) VALUES (1267,"surrande: brummande, sus, sorl");
INSERT INTO nameTable (id,item) VALUES (1268,"välde: makt, rike");
INSERT INTO nameTable (id,item) VALUES (1269,"dåsig: sömnig");
INSERT INTO nameTable (id,item) VALUES (1270,"sporre: stimulans, vass spets på en ridstövel som används av ryttare för att driva på häst");
INSERT INTO nameTable (id,item) VALUES (1271,"sporra: driva på, egga, stimulera");
INSERT INTO nameTable (id,item) VALUES (1272,"knappnål: nål med huvud, pin");
INSERT INTO nameTable (id,item) VALUES (1273,"brus: starkt väsande ljud");
INSERT INTO nameTable (id,item) VALUES (1274,"brusa upp: plötsligt bli arg");
INSERT INTO nameTable (id,item) VALUES (1275,"Frid vare med: Peace be with");
INSERT INTO nameTable (id,item) VALUES (1276,"trotsa: göra öppen motstånd mot");
INSERT INTO nameTable (id,item) VALUES (1277,"slunga: kasta häftigt");
INSERT INTO nameTable (id,item) VALUES (1278,"projektil: föremål som skjuts iväg, skott");
INSERT INTO nameTable (id,item) VALUES (1279,"bräcka: bryta, knäcka");
INSERT INTO nameTable (id,item) VALUES (1280,"tuva: liten gräsbeväxt upphöjning i marken");
INSERT INTO nameTable (id,item) VALUES (1281,"barmhärtig: godhjärtd, medlidsam, merciful");
INSERT INTO nameTable (id,item) VALUES (1282,"begången/begånget: begått");
INSERT INTO nameTable (id,item) VALUES (1283,"3.3 Mannen på ön");
INSERT INTO nameTable (id,item) VALUES (1284,"uppenbarelse: varelse, syn, insikt, vision");
INSERT INTO nameTable (id,item) VALUES (1285,"bestämbar: definierbar, urskiljbar");
INSERT INTO nameTable (id,item) VALUES (1286,"skära: kort halvcirkelformat lie");
INSERT INTO nameTable (id,item) VALUES (1287,"utvilad: som har vilat tillräckligt, pigg");
INSERT INTO nameTable (id,item) VALUES (1288,"märkvärdig: egendomlig, speciell");
INSERT INTO nameTable (id,item) VALUES (1289,"hjort: hovdjur med greniga horn, deer");
INSERT INTO nameTable (id,item) VALUES (1290,"erinra: komma ihåg, påminna");
INSERT INTO nameTable (id,item) VALUES (1291,"vara på vippen att: be on the point of");
INSERT INTO nameTable (id,item) VALUES (1292,"anlete: ansikt");
INSERT INTO nameTable (id,item) VALUES (1293,"anletsdrag: ansiktsuttryck, utseende");
INSERT INTO nameTable (id,item) VALUES (1294,"olikartad: olika slags, different");
INSERT INTO nameTable (id,item) VALUES (1295,"stump: kort bit, sista bit, end");
INSERT INTO nameTable (id,item) VALUES (1296,"utstyrsel: kläder, dräkt");
INSERT INTO nameTable (id,item) VALUES (1297,"varvid: vid vilket tillfälle, och då");
INSERT INTO nameTable (id,item) VALUES (1298,"rabbla: läsa upp snabbt");
INSERT INTO nameTable (id,item) VALUES (1299,"katekes: lärobok i kristendomens huvudstycken");
INSERT INTO nameTable (id,item) VALUES (1300,"singla: falla med svängande rörelse till marken");
INSERT INTO nameTable (id,item) VALUES (1301,"singla slant: kasta ett mynt för att bestämma");
INSERT INTO nameTable (id,item) VALUES (1302,"försyn: Guds omsorg, öde");
INSERT INTO nameTable (id,item) VALUES (1303,"hötta/hytta: hotfullt skaka näven eller fingret");
INSERT INTO nameTable (id,item) VALUES (1304,"hälsa hem: att det kommer att gå vederbörande illa");
INSERT INTO nameTable (id,item) VALUES (1305,"knipa: tillfälligt besvärligt situation, svårighet");
INSERT INTO nameTable (id,item) VALUES (1306,"livré: tjänstedräkt");
INSERT INTO nameTable (id,item) VALUES (1307,"bära sig åt: uppföra sig");
INSERT INTO nameTable (id,item) VALUES (1308,"därvid: vid denna");
INSERT INTO nameTable (id,item) VALUES (1309,"återkasta: reflektera");
INSERT INTO nameTable (id,item) VALUES (1310,"beder: bee, böna, pray");
INSERT INTO nameTable (id,item) VALUES (1311,"gevärssalva: samtidigt avfyrning av fera gevär");
INSERT INTO nameTable (id,item) VALUES (1314,"4.1 Hur skeppet övergavs");
INSERT INTO nameTable (id,item) VALUES (1315,"övermanna: besegra");
INSERT INTO nameTable (id,item) VALUES (1316,"slinka: smita");
INSERT INTO nameTable (id,item) VALUES (1317,"oviss: inte säker, tveksam");
INSERT INTO nameTable (id,item) VALUES (1318,"skarv: gräns mellan två delar, övergång");
INSERT INTO nameTable (id,item) VALUES (1319,"stank: vidrig lukt, odör");
INSERT INTO nameTable (id,item) VALUES (1320,"dysenteri: en tarmsjukdom");
INSERT INTO nameTable (id,item) VALUES (1321,"gorma: skälla, gräla");
INSERT INTO nameTable (id,item) VALUES (1322,"förtöja: lägga fast med rep");
INSERT INTO nameTable (id,item) VALUES (1323,"back: 1. backåtväxel på en båt/bil 2. låda 3. försvarsspelare i idrott");
INSERT INTO nameTable (id,item) VALUES (1324,"jolle: liten roddbåt");
INSERT INTO nameTable (id,item) VALUES (1325,"rekognoscera: undersöka, utforska, recognize");
INSERT INTO nameTable (id,item) VALUES (1326,"villrådig: osäker om hur man ska handla, tveksam");
INSERT INTO nameTable (id,item) VALUES (1327,"skjuta ut: sticka fram");
INSERT INTO nameTable (id,item) VALUES (1328,"svalka: kyla");
INSERT INTO nameTable (id,item) VALUES (1329,"välla: rinna i stora mängder, flöda, strömma");
INSERT INTO nameTable (id,item) VALUES (1330,"röja: 1. städa, rensa upp, 2. odla upp, 3. avslöja");
INSERT INTO nameTable (id,item) VALUES (1331,"belägra: omringa för att tvinga försvarare att ge upp");
INSERT INTO nameTable (id,item) VALUES (1332,"rapphöns: en vilt fågel som man gillar att jaga");
INSERT INTO nameTable (id,item) VALUES (1333,"fördra: kräva, begära");
INSERT INTO nameTable (id,item) VALUES (1334,"proviant: livsmedel, matförråd");
INSERT INTO nameTable (id,item) VALUES (1335,"överrumpla: överraska");
INSERT INTO nameTable (id,item) VALUES (1338,"ty: eftersom, därför att, för");
INSERT INTO nameTable (id,item) VALUES (1339,"hertig: titel för manlig medlem av kungahuset");
INSERT INTO nameTable (id,item) VALUES (1340,"uppskakad: chockad, rädd");
INSERT INTO nameTable (id,item) VALUES (1341,"lärft: tätvävda vita tyger");
INSERT INTO nameTable (id,item) VALUES (1342,"vara illa däran: vara svårt skadad eller sjuk");
INSERT INTO nameTable (id,item) VALUES (1343,"gå till väga: göra något på ett visst sätt");
INSERT INTO nameTable (id,item) VALUES (1344,"konjak: en dyr spritdryck");
INSERT INTO nameTable (id,item) VALUES (1345,"ovärderlig: som inte kan värderas i pengar");
INSERT INTO nameTable (id,item) VALUES (1346,"anföra: leda, ge order");
INSERT INTO nameTable (id,item) VALUES (1347,"han är dödens: han är dödens lammunge");
INSERT INTO nameTable (id,item) VALUES (1348,"åtskillig: mycket, en hel del");
INSERT INTO nameTable (id,item) VALUES (1349,"rådplägning: debatt, samråd, diskussion");
INSERT INTO nameTable (id,item) VALUES (1350,"tripp: trip");
INSERT INTO nameTable (id,item) VALUES (1351,"börda: last, belastning");
INSERT INTO nameTable (id,item) VALUES (1352,"fatta posto: inta försvarsställning, ställa sig");
INSERT INTO nameTable (id,item) VALUES (1353,"oskadliggöra: desarmera");
INSERT INTO nameTable (id,item) VALUES (1354,"fånglina: förtöjningslina på båt");
INSERT INTO nameTable (id,item) VALUES (1355,"för brinnande livet: av alla krafter, i full fart");
INSERT INTO nameTable (id,item) VALUES (1356,"lämpa över bord: kasta i vattnet från ett fartyg");
INSERT INTO nameTable (id,item) VALUES (1357,"hojta: anropa högt");
INSERT INTO nameTable (id,item) VALUES (1358,"bege sig iväg: åka iväg");
INSERT INTO nameTable (id,item) VALUES (1359,"vräka: 1. våldsamt kasta, 2. (med lagens hjälp) köra ut en hyresgässt från en lägenhet");
INSERT INTO nameTable (id,item) VALUES (1360,"4.2 Jollens sista färd");
INSERT INTO nameTable (id,item) VALUES (1361,"därtill: dessutom, även, in addition");
INSERT INTO nameTable (id,item) VALUES (1362,"inhägnad: område innanför stängsel");
INSERT INTO nameTable (id,item) VALUES (1363,"kantra: välta, kapsejsa");
INSERT INTO nameTable (id,item) VALUES (1364,"hålla av: 1. edge away (to move contiously away from something), 2. tycka om, älska");
INSERT INTO nameTable (id,item) VALUES (1365,"stäv: fartygs förända eller akterända");
INSERT INTO nameTable (id,item) VALUES (1366,"orda: tala");
INSERT INTO nameTable (id,item) VALUES (1367,"bombaremang: bombardment");
INSERT INTO nameTable (id,item) VALUES (1368,"presenning: stort tygstycke som används till skydd");
INSERT INTO nameTable (id,item) VALUES (1369,"skytt: person som skjuter");
INSERT INTO nameTable (id,item) VALUES (1370,"rödbrusig: rödflammig i ansiktet av uphetning, sprit");
INSERT INTO nameTable (id,item) VALUES (1371,"stjälpa: välta, kantra");
INSERT INTO nameTable (id,item) VALUES (1372,"rodd: ro");
INSERT INTO nameTable (id,item) VALUES (1373,"laddstock: stake av trä, järn eller fjäderstål varmed skottet medförs i pipan på eldvapen för framladdning");
INSERT INTO nameTable (id,item) VALUES (1374,"utstöta: 1. frambringa häftigt ljud, 2. utesluta");
INSERT INTO nameTable (id,item) VALUES (1375,"säga till: befalla, uppmana, ge order");
INSERT INTO nameTable (id,item) VALUES (1376,"årtag: rodd, stroke");
INSERT INTO nameTable (id,item) VALUES (1377,"betraktande: consideration");
INSERT INTO nameTable (id,item) VALUES (1378,"i betraktande av: med hänsyn till");
INSERT INTO nameTable (id,item) VALUES (1379,"bryn: utkant");
INSERT INTO nameTable (id,item) VALUES (1380,"knäppa: smälla, fästa ihop");
INSERT INTO nameTable (id,item) VALUES (1381,"vada: gå i grunt vatten");
INSERT INTO nameTable (id,item) VALUES (1382,"4.3 Slutet på första dagens strid");
INSERT INTO nameTable (id,item) VALUES (1383,"remsa: smalt band");
INSERT INTO nameTable (id,item) VALUES (1384,"sammandrabbning: sammanstötning");
INSERT INTO nameTable (id,item) VALUES (1385,"klinga: blad på svärt, såg");
INSERT INTO nameTable (id,item) VALUES (1386,"vina: vissla, ge ifrån sig ett högt och gällt och ihållande ljud");
INSERT INTO nameTable (id,item) VALUES (1387,"göra skäl för: vara värd");
INSERT INTO nameTable (id,item) VALUES (1388,"vackla: vara nära att falla, svikta, stappl");
INSERT INTO nameTable (id,item) VALUES (1389,"falla på sin post: dö av sin tjänst");
INSERT INTO nameTable (id,item) VALUES (1390,"skingra: splittra åt olika håll");
INSERT INTO nameTable (id,item) VALUES (1391,"stöna: ge ifrån sig ett dovt och utdraget ljud av smärta");
INSERT INTO nameTable (id,item) VALUES (1392,"trumpen: butter och missnöjd, grinig");
INSERT INTO nameTable (id,item) VALUES (1393,"sittopp: smäll, slag");
INSERT INTO nameTable (id,item) VALUES (1394,"bruklig: vanlig, användbar");
INSERT INTO nameTable (id,item) VALUES (1395,"urskuldande: ursäktande");
INSERT INTO nameTable (id,item) VALUES (1396,"inventera: genomgå och granska, kontrollera");
INSERT INTO nameTable (id,item) VALUES (1397,"vördnad: respekt, heder");
INSERT INTO nameTable (id,item) VALUES (1398,"husbonde: herre, arbetsgivare, ägare");
INSERT INTO nameTable (id,item) VALUES (1399,"undsätta: rädda, befria, hjälpa (i svårt)");
INSERT INTO nameTable (id,item) VALUES (1400,"undsättningsexpedition: rescue mission");
INSERT INTO nameTable (id,item) VALUES (1401,"nådig: barmhärtig, välvillig");
INSERT INTO nameTable (id,item) VALUES (1402,"barskrapad: utfattig");
INSERT INTO nameTable (id,item) VALUES (1403,"ranson: tilldelning");
INSERT INTO nameTable (id,item) VALUES (1404,"stryka: 1. ta bort, 2. dra med handen över, 3. släta till med strykjärn");
INSERT INTO nameTable (id,item) VALUES (1405,"utslag: 1. beslut, 2. uttryck, 3. blåsor på huden");
INSERT INTO nameTable (id,item) VALUES (1406,"rikoschett: projektil som studsar och fortsätter i en ny bana");
INSERT INTO nameTable (id,item) VALUES (1407,"ödsla: slösa");
INSERT INTO nameTable (id,item) VALUES (1408,"anmärka: påpeka");
INSERT INTO nameTable (id,item) VALUES (1409,"upplag: förråd");
INSERT INTO nameTable (id,item) VALUES (1410,"timmer: grovt osågat trä, stock");
INSERT INTO nameTable (id,item) VALUES (1411,"timmerman: träarbetare på byggarbetsplats, snickare");
INSERT INTO nameTable (id,item) VALUES (1412,"de enda: the only ones");
