DELETE FROM nameTable;
INSERT INTO nameTable (id,item) VALUES (1,"Root");
INSERT INTO nameTable (id,item) VALUES (2,"Matte");
INSERT INTO nameTable (id,item) VALUES (3,"Fysik");
INSERT INTO nameTable (id,item) VALUES (4,"Kemi");
INSERT INTO nameTable (id,item) VALUES (5,"Biologi");
INSERT INTO nameTable (id,item) VALUES (6,"Geografi");
INSERT INTO nameTable (id,item) VALUES (7,"Historia");
INSERT INTO nameTable (id,item) VALUES (8,"Religion");
INSERT INTO nameTable (id,item) VALUES (9,"Samhälle");
INSERT INTO nameTable (id,item) VALUES (10,"Flat");
INSERT INTO nameTable (id,item) VALUES (11,"1");
INSERT INTO nameTable (id,item) VALUES (12,"ax+b");
INSERT INTO nameTable (id,item) VALUES (13,"ax²+bx+c");
INSERT INTO nameTable (id,item) VALUES (14,"ax³+bx²+cx+d");
INSERT INTO nameTable (id,item) VALUES (15,"lg(x)");
INSERT INTO nameTable (id,item) VALUES (16,"sin(x)");
INSERT INTO nameTable (id,item) VALUES (17,"tan(x)");
INSERT INTO nameTable (id,item) VALUES (18,"!");
INSERT INTO nameTable (id,item) VALUES (19,"(1) Linje");
INSERT INTO nameTable (id,item) VALUES (20,"(3) Triangel");
INSERT INTO nameTable (id,item) VALUES (21,"(4) Fyrhörning");
INSERT INTO nameTable (id,item) VALUES (22,"(...) Polygon");
INSERT INTO nameTable (id,item) VALUES (23,"P.E.F=G*m1*m2/r²=ma");
INSERT INTO nameTable (id,item) VALUES (24,"P=IV ΣU=ΣIR");
INSERT INTO nameTable (id,item) VALUES (25,"Cirkel");
INSERT INTO nameTable (id,item) VALUES (26,"Hyperbel");
INSERT INTO nameTable (id,item) VALUES (27,"2");
INSERT INTO nameTable (id,item) VALUES (28,"(H) Väte");
INSERT INTO nameTable (id,item) VALUES (29,"(He) Helium");
INSERT INTO nameTable (id,item) VALUES (30,"(Li) Litium");
INSERT INTO nameTable (id,item) VALUES (31,"(Be) Beryllium");
INSERT INTO nameTable (id,item) VALUES (32,"(B) Bor");
INSERT INTO nameTable (id,item) VALUES (33,"(C) Kol");
INSERT INTO nameTable (id,item) VALUES (34,"(N) Kväve");
INSERT INTO nameTable (id,item) VALUES (35,"(O) Syre");
INSERT INTO nameTable (id,item) VALUES (36,"(F) Flour");
INSERT INTO nameTable (id,item) VALUES (37,"(Ne) Neon");
INSERT INTO nameTable (id,item) VALUES (38,"(Na) Natrium");
INSERT INTO nameTable (id,item) VALUES (39,"(Mg) Magnesium");
INSERT INTO nameTable (id,item) VALUES (40,"(Al) Aluminium");
INSERT INTO nameTable (id,item) VALUES (41,"(Si) Kisel");
INSERT INTO nameTable (id,item) VALUES (42,"(P) Fosfor");
INSERT INTO nameTable (id,item) VALUES (43,"(S) Svavel");
INSERT INTO nameTable (id,item) VALUES (44,"(Cl) Klor");
INSERT INTO nameTable (id,item) VALUES (45,"(Ar) Argon");
INSERT INTO nameTable (id,item) VALUES (46,"Kolväte");
INSERT INTO nameTable (id,item) VALUES (47,"1");
INSERT INTO nameTable (id,item) VALUES (48,"1");
INSERT INTO nameTable (id,item) VALUES (49,"2");
INSERT INTO nameTable (id,item) VALUES (50,"3");
INSERT INTO nameTable (id,item) VALUES (51,"4");
INSERT INTO nameTable (id,item) VALUES (52,"5");
INSERT INTO nameTable (id,item) VALUES (53,"6");
INSERT INTO nameTable (id,item) VALUES (54,"7");
INSERT INTO nameTable (id,item) VALUES (55,"8");
INSERT INTO nameTable (id,item) VALUES (56,"9");
INSERT INTO nameTable (id,item) VALUES (57,"...");
INSERT INTO nameTable (id,item) VALUES (58,"(-OH) Alkohol");
INSERT INTO nameTable (id,item) VALUES (59,"Gummi");
INSERT INTO nameTable (id,item) VALUES (60,"Fiber");
INSERT INTO nameTable (id,item) VALUES (61,"Plast");
INSERT INTO nameTable (id,item) VALUES (62,"Lipid (Fett)");
INSERT INTO nameTable (id,item) VALUES (63,"Kolhydrater");
INSERT INTO nameTable (id,item) VALUES (64,"Glykos");
INSERT INTO nameTable (id,item) VALUES (65,"Fruktos");
INSERT INTO nameTable (id,item) VALUES (66,"Stäkelse");
INSERT INTO nameTable (id,item) VALUES (67,"Tensid");
INSERT INTO nameTable (id,item) VALUES (68,"Protein");
INSERT INTO nameTable (id,item) VALUES (69,"Enzym");
INSERT INTO nameTable (id,item) VALUES (70,"Vitamin");
INSERT INTO nameTable (id,item) VALUES (71,"Vitamin");
INSERT INTO nameTable (id,item) VALUES (72,"DNA");
INSERT INTO nameTable (id,item) VALUES (73,"Läkemedel");
INSERT INTO nameTable (id,item) VALUES (74,"Giftiga ämnen");
INSERT INTO nameTable (id,item) VALUES (75,"Algebra");
INSERT INTO nameTable (id,item) VALUES (76,"Geometri");
INSERT INTO nameTable (id,item) VALUES (77,"Analytisk geometri");
