DELETE FROM nameTable;
INSERT INTO nameTable (id,item) VALUES (1,"Root");
INSERT INTO nameTable (id,item) VALUES (2,"Matte");
INSERT INTO nameTable (id,item) VALUES (3,"Fysik");
INSERT INTO nameTable (id,item) VALUES (4,"Kemi");
INSERT INTO nameTable (id,item) VALUES (5,"Biologi");
INSERT INTO nameTable (id,item) VALUES (6,"Geografi");
INSERT INTO nameTable (id,item) VALUES (7,"Historia");
INSERT INTO nameTable (id,item) VALUES (8,"Religion");
INSERT INTO nameTable (id,item) VALUES (9,"Samhälle");
INSERT INTO nameTable (id,item) VALUES (10,"ax+b");
INSERT INTO nameTable (id,item) VALUES (11,"ax²+bx+c");
INSERT INTO nameTable (id,item) VALUES (12,"ax³+bx²+cx+d");
INSERT INTO nameTable (id,item) VALUES (13,"lg(x)");
INSERT INTO nameTable (id,item) VALUES (14,"sin(x)");
INSERT INTO nameTable (id,item) VALUES (15,"tan(x)");
INSERT INTO nameTable (id,item) VALUES (16,"!");
INSERT INTO nameTable (id,item) VALUES (17,"(1) Linje");
INSERT INTO nameTable (id,item) VALUES (18,"(3) Triangel");
INSERT INTO nameTable (id,item) VALUES (19,"(4) Fyrhörning");
INSERT INTO nameTable (id,item) VALUES (20,"(...) Polygon");
INSERT INTO nameTable (id,item) VALUES (21,"Cirkel");
INSERT INTO nameTable (id,item) VALUES (22,"Hyperbel");
INSERT INTO nameTable (id,item) VALUES (23,"(H) Väte");
INSERT INTO nameTable (id,item) VALUES (24,"(He) Helium");
INSERT INTO nameTable (id,item) VALUES (25,"(Li) Litium");
INSERT INTO nameTable (id,item) VALUES (26,"(Be) Beryllium");
INSERT INTO nameTable (id,item) VALUES (27,"(B) Bor");
INSERT INTO nameTable (id,item) VALUES (28,"(C) Kol");
INSERT INTO nameTable (id,item) VALUES (29,"(N) Kväve");
INSERT INTO nameTable (id,item) VALUES (30,"(O) Syre");
INSERT INTO nameTable (id,item) VALUES (31,"(F) Flour");
INSERT INTO nameTable (id,item) VALUES (32,"(Ne) Neon");
INSERT INTO nameTable (id,item) VALUES (33,"(Na) Natrium");
INSERT INTO nameTable (id,item) VALUES (34,"(Mg) Magnesium");
INSERT INTO nameTable (id,item) VALUES (35,"(Al) Aluminium");
INSERT INTO nameTable (id,item) VALUES (36,"(Si) Kisel");
INSERT INTO nameTable (id,item) VALUES (37,"(P) Fosfor");
INSERT INTO nameTable (id,item) VALUES (38,"(S) Svavel");
INSERT INTO nameTable (id,item) VALUES (39,"(Cl) Klor");
INSERT INTO nameTable (id,item) VALUES (40,"(Ar) Argon");
INSERT INTO nameTable (id,item) VALUES (41,"Kolväte");
INSERT INTO nameTable (id,item) VALUES (42,"(-OH) Alkohol");
INSERT INTO nameTable (id,item) VALUES (43,"Gummi");
INSERT INTO nameTable (id,item) VALUES (44,"Fiber");
INSERT INTO nameTable (id,item) VALUES (45,"Plast");
INSERT INTO nameTable (id,item) VALUES (46,"Lipid (Fett)");
INSERT INTO nameTable (id,item) VALUES (47,"Kolhydrater");
INSERT INTO nameTable (id,item) VALUES (48,"Glykos");
INSERT INTO nameTable (id,item) VALUES (49,"Fruktos");
INSERT INTO nameTable (id,item) VALUES (50,"Stäkelse");
INSERT INTO nameTable (id,item) VALUES (51,"Tensid");
INSERT INTO nameTable (id,item) VALUES (52,"Protein");
INSERT INTO nameTable (id,item) VALUES (53,"Enzym");
INSERT INTO nameTable (id,item) VALUES (54,"Vitamin");
INSERT INTO nameTable (id,item) VALUES (55,"Vitamin");
INSERT INTO nameTable (id,item) VALUES (56,"DNA");
INSERT INTO nameTable (id,item) VALUES (57,"Läkemedel");
INSERT INTO nameTable (id,item) VALUES (58,"Giftiga ämnen");
INSERT INTO nameTable (id,item) VALUES (59,"Algebra");
INSERT INTO nameTable (id,item) VALUES (60,"Geometri");
INSERT INTO nameTable (id,item) VALUES (61,"Analytisk geometri");
INSERT INTO nameTable (id,item) VALUES (62,"Objektegenskap");
INSERT INTO nameTable (id,item) VALUES (63,"Position och vinklar");
INSERT INTO nameTable (id,item) VALUES (64,"Former");
INSERT INTO nameTable (id,item) VALUES (65,"Färg");
INSERT INTO nameTable (id,item) VALUES (66,"Textur");
INSERT INTO nameTable (id,item) VALUES (67,"(x, y, z, α)(bred, höjd, längd)");
INSERT INTO nameTable (id,item) VALUES (68,"Gul");
INSERT INTO nameTable (id,item) VALUES (69,"Röd");
INSERT INTO nameTable (id,item) VALUES (70,"Grön");
INSERT INTO nameTable (id,item) VALUES (71,"Blå");
INSERT INTO nameTable (id,item) VALUES (72,"Grå");
INSERT INTO nameTable (id,item) VALUES (73,"Svart");
INSERT INTO nameTable (id,item) VALUES (74,"Vit");
INSERT INTO nameTable (id,item) VALUES (75,"Brun");
INSERT INTO nameTable (id,item) VALUES (76,"Orange");
INSERT INTO nameTable (id,item) VALUES (77,"Lila");
INSERT INTO nameTable (id,item) VALUES (78,"Beige");
INSERT INTO nameTable (id,item) VALUES (79,"Turkos");
INSERT INTO nameTable (id,item) VALUES (80,"Kaki");
INSERT INTO nameTable (id,item) VALUES (81,"Akvamarin");
INSERT INTO nameTable (id,item) VALUES (82,"Crimson");
INSERT INTO nameTable (id,item) VALUES (83,"Cream");
INSERT INTO nameTable (id,item) VALUES (84,"Scarlet");
INSERT INTO nameTable (id,item) VALUES (85,"Fyllning");
INSERT INTO nameTable (id,item) VALUES (86,"Gräns");
INSERT INTO nameTable (id,item) VALUES (87,"Skugga/Glöd");
INSERT INTO nameTable (id,item) VALUES (88,"Hård");
INSERT INTO nameTable (id,item) VALUES (89,"Grov");
INSERT INTO nameTable (id,item) VALUES (90,"Mjuk");
INSERT INTO nameTable (id,item) VALUES (91,"Slät");
INSERT INTO nameTable (id,item) VALUES (92,"Spetsig");
INSERT INTO nameTable (id,item) VALUES (93,"Ojämn");
INSERT INTO nameTable (id,item) VALUES (94,"⊥: a1*a2 = -1");
INSERT INTO nameTable (id,item) VALUES (95,"∥: a1 = a2");
INSERT INTO nameTable (id,item) VALUES (96,"^B=^C");
INSERT INTO nameTable (id,item) VALUES (97,"AB=AC");
INSERT INTO nameTable (id,item) VALUES (98,"^=60°/=");
INSERT INTO nameTable (id,item) VALUES (99,"AB∥CD & AC∥BD");
INSERT INTO nameTable (id,item) VALUES (100,"^A = ^D & ^B = ^C");
INSERT INTO nameTable (id,item) VALUES (101,"x=(-b+√(b²-4ac)");
INSERT INTO nameTable (id,item) VALUES (102,"Kvadreringsregler");
INSERT INTO nameTable (id,item) VALUES (103,"(a+b)²=a²+2ab+b²");
INSERT INTO nameTable (id,item) VALUES (104,"(a-b)²=a²-2ab+b²");
INSERT INTO nameTable (id,item) VALUES (105,"lg(ab) = lg(a)+lg(b)");
INSERT INTO nameTable (id,item) VALUES (106,"a/sin(A) = b/sin(B) = c/sin(C)");
INSERT INTO nameTable (id,item) VALUES (107,"sin²(x)+cos²(x)=1");
INSERT INTO nameTable (id,item) VALUES (108,"c²=a²+b²-2abcos(C)");
INSERT INTO nameTable (id,item) VALUES (109,"nPr=n!/(n-r)!");
INSERT INTO nameTable (id,item) VALUES (110,"nCr=nPr/r!");
INSERT INTO nameTable (id,item) VALUES (111,"∫");
INSERT INTO nameTable (id,item) VALUES (112,"Δ/Δt");
INSERT INTO nameTable (id,item) VALUES (113,"Δ/Δx(ax^b) = abx^(b-1)");
INSERT INTO nameTable (id,item) VALUES (114,"Jorden");
INSERT INTO nameTable (id,item) VALUES (115,"Luft");
INSERT INTO nameTable (id,item) VALUES (116,"Jord");
INSERT INTO nameTable (id,item) VALUES (117,"Marknivå");
INSERT INTO nameTable (id,item) VALUES (118,"Vatten");
INSERT INTO nameTable (id,item) VALUES (119,"Naturresurser");
INSERT INTO nameTable (id,item) VALUES (120,"Miljö och klimat");
INSERT INTO nameTable (id,item) VALUES (121,"Atmosfär");
INSERT INTO nameTable (id,item) VALUES (122,"Troposfär (11km)");
INSERT INTO nameTable (id,item) VALUES (123,"Stratosfär (30km)");
INSERT INTO nameTable (id,item) VALUES (124,"Jonosfär (100km)");
INSERT INTO nameTable (id,item) VALUES (125,"Inre krafter");
INSERT INTO nameTable (id,item) VALUES (126,"Yttre krafter");
INSERT INTO nameTable (id,item) VALUES (127,"Vulkanism");
INSERT INTO nameTable (id,item) VALUES (128,"Sprickor");
INSERT INTO nameTable (id,item) VALUES (129,"Mantel");
INSERT INTO nameTable (id,item) VALUES (130,"Magma");
INSERT INTO nameTable (id,item) VALUES (131,"Förvittring");
INSERT INTO nameTable (id,item) VALUES (132,"Deposition");
INSERT INTO nameTable (id,item) VALUES (133,"Jordbävning");
INSERT INTO nameTable (id,item) VALUES (134,"sprucken jord");
INSERT INTO nameTable (id,item) VALUES (135,"Kontinentaldrift");
INSERT INTO nameTable (id,item) VALUES (136,"Berggrund");
INSERT INTO nameTable (id,item) VALUES (137,"Granit");
INSERT INTO nameTable (id,item) VALUES (138,"Sandsten");
INSERT INTO nameTable (id,item) VALUES (139,"Gnejs");
INSERT INTO nameTable (id,item) VALUES (140,"Olja(Petroleum)");
INSERT INTO nameTable (id,item) VALUES (141,"Gas");
INSERT INTO nameTable (id,item) VALUES (142,"Kol");
INSERT INTO nameTable (id,item) VALUES (143,"Mineraler");
INSERT INTO nameTable (id,item) VALUES (144,"Sand");
INSERT INTO nameTable (id,item) VALUES (145,"Sten");
INSERT INTO nameTable (id,item) VALUES (146,"Vatten");
INSERT INTO nameTable (id,item) VALUES (147,"Mark");
INSERT INTO nameTable (id,item) VALUES (148,"Högre temperatur");
INSERT INTO nameTable (id,item) VALUES (149,"Högre halt koldioxid");
INSERT INTO nameTable (id,item) VALUES (150,"Extrem klimat");
INSERT INTO nameTable (id,item) VALUES (151,"Vattenbrist");
INSERT INTO nameTable (id,item) VALUES (152,"Verktyg");
INSERT INTO nameTable (id,item) VALUES (153,"Penna");
INSERT INTO nameTable (id,item) VALUES (154,"Blyertspenna");
INSERT INTO nameTable (id,item) VALUES (155,"Pensel");
INSERT INTO nameTable (id,item) VALUES (156,"Skrivande");
INSERT INTO nameTable (id,item) VALUES (157,"Märkpenna");
INSERT INTO nameTable (id,item) VALUES (158,"Bläck");
INSERT INTO nameTable (id,item) VALUES (159,"Borttagande");
INSERT INTO nameTable (id,item) VALUES (160,"Suddgummi");
INSERT INTO nameTable (id,item) VALUES (161,"Tipex");
INSERT INTO nameTable (id,item) VALUES (162,"Korrektionspenna");
INSERT INTO nameTable (id,item) VALUES (163,"Yta");
INSERT INTO nameTable (id,item) VALUES (164,"Andra verktyg");
INSERT INTO nameTable (id,item) VALUES (165,"Papper");
INSERT INTO nameTable (id,item) VALUES (166,"Skrivbok");
INSERT INTO nameTable (id,item) VALUES (167,"Tavla");
INSERT INTO nameTable (id,item) VALUES (168,"Pennvässare");
INSERT INTO nameTable (id,item) VALUES (169,"Linjal");
INSERT INTO nameTable (id,item) VALUES (170,"Cirkelpassare");
INSERT INTO nameTable (id,item) VALUES (171,"Klämmor");
INSERT INTO nameTable (id,item) VALUES (172,"Häftare");
INSERT INTO nameTable (id,item) VALUES (173,"Dator");
INSERT INTO nameTable (id,item) VALUES (174,"GUI");
INSERT INTO nameTable (id,item) VALUES (175,"Hårdvaror");
INSERT INTO nameTable (id,item) VALUES (176,"Lagring");
INSERT INTO nameTable (id,item) VALUES (177,"Typer");
INSERT INTO nameTable (id,item) VALUES (178,"Mjukvaror");
INSERT INTO nameTable (id,item) VALUES (179,"CoordinatorLayout");
INSERT INTO nameTable (id,item) VALUES (180,"LinearLayout");
INSERT INTO nameTable (id,item) VALUES (181,"Text");
INSERT INTO nameTable (id,item) VALUES (182,"Img");
INSERT INTO nameTable (id,item) VALUES (183,"Knapplista");
INSERT INTO nameTable (id,item) VALUES (184,"Tabell");
INSERT INTO nameTable (id,item) VALUES (185,"Form");
INSERT INTO nameTable (id,item) VALUES (186,"Sidorad");
INSERT INTO nameTable (id,item) VALUES (187,"Header");
INSERT INTO nameTable (id,item) VALUES (188,"Lightbox");
INSERT INTO nameTable (id,item) VALUES (189,"Inmatning");
INSERT INTO nameTable (id,item) VALUES (190,"Välj");
INSERT INTO nameTable (id,item) VALUES (191,"Kryssruta");
INSERT INTO nameTable (id,item) VALUES (192,"Markör");
INSERT INTO nameTable (id,item) VALUES (193,"Upplösning");
INSERT INTO nameTable (id,item) VALUES (194,"Processor");
INSERT INTO nameTable (id,item) VALUES (195,"CPU");
INSERT INTO nameTable (id,item) VALUES (196,"Grafik");
INSERT INTO nameTable (id,item) VALUES (197,"Nätverk");
INSERT INTO nameTable (id,item) VALUES (198,"Powersupply");
INSERT INTO nameTable (id,item) VALUES (199,"RAM");
INSERT INTO nameTable (id,item) VALUES (200,"Hårddisk");
INSERT INTO nameTable (id,item) VALUES (201,"Databas");
INSERT INTO nameTable (id,item) VALUES (202,"Mapp");
INSERT INTO nameTable (id,item) VALUES (203,"Fil");
INSERT INTO nameTable (id,item) VALUES (204,"Genväg");
INSERT INTO nameTable (id,item) VALUES (205,"Ikon");
INSERT INTO nameTable (id,item) VALUES (206,"Verktygsfält");
INSERT INTO nameTable (id,item) VALUES (207,"Stationär Dator");
INSERT INTO nameTable (id,item) VALUES (208,"Bärbar dator");
INSERT INTO nameTable (id,item) VALUES (209,"Surfplatta(Padda)");
INSERT INTO nameTable (id,item) VALUES (210,"Mobiltelefon");
INSERT INTO nameTable (id,item) VALUES (211,"Smartklocka");
INSERT INTO nameTable (id,item) VALUES (212,"Robot");
INSERT INTO nameTable (id,item) VALUES (213,"Superdator");
INSERT INTO nameTable (id,item) VALUES (214,"Mainframe");
INSERT INTO nameTable (id,item) VALUES (215,"Programmeringspråk");
INSERT INTO nameTable (id,item) VALUES (216,"Datastruktur");
INSERT INTO nameTable (id,item) VALUES (217,"Algorithm");
INSERT INTO nameTable (id,item) VALUES (218,"Vapen");
INSERT INTO nameTable (id,item) VALUES (219,"Knivform");
INSERT INTO nameTable (id,item) VALUES (220,"Kniv");
INSERT INTO nameTable (id,item) VALUES (221,"Machete");
INSERT INTO nameTable (id,item) VALUES (222,"Svärd");
INSERT INTO nameTable (id,item) VALUES (223,"Sabel");
INSERT INTO nameTable (id,item) VALUES (224,"Spear");
INSERT INTO nameTable (id,item) VALUES (225,"Hammare");
INSERT INTO nameTable (id,item) VALUES (226,"Ringform");
INSERT INTO nameTable (id,item) VALUES (227,"Yxform");
INSERT INTO nameTable (id,item) VALUES (228,"Mekanisk Skjutvapen");
INSERT INTO nameTable (id,item) VALUES (229,"Advancerad Mekanisk Skjutvapen");
INSERT INTO nameTable (id,item) VALUES (230,"Skjutvapen");
INSERT INTO nameTable (id,item) VALUES (231,"Bombform");
INSERT INTO nameTable (id,item) VALUES (232,"Knuckles-metall");
INSERT INTO nameTable (id,item) VALUES (233,"Shuriken");
INSERT INTO nameTable (id,item) VALUES (234,"Lasso");
INSERT INTO nameTable (id,item) VALUES (235,"Nunchaku");
INSERT INTO nameTable (id,item) VALUES (236,"Yxa");
INSERT INTO nameTable (id,item) VALUES (237,"Tomahawk");
INSERT INTO nameTable (id,item) VALUES (238,"Mace");
INSERT INTO nameTable (id,item) VALUES (239,"Pilbåge");
INSERT INTO nameTable (id,item) VALUES (240,"Pil");
INSERT INTO nameTable (id,item) VALUES (241,"Armborst");
INSERT INTO nameTable (id,item) VALUES (242,"Katapult");
INSERT INTO nameTable (id,item) VALUES (243,"Bajonett");
INSERT INTO nameTable (id,item) VALUES (244,"Ballista");
INSERT INTO nameTable (id,item) VALUES (245,"Harpun");
INSERT INTO nameTable (id,item) VALUES (246,"Arquebus");
INSERT INTO nameTable (id,item) VALUES (247,"Molotov coctail");
INSERT INTO nameTable (id,item) VALUES (248,"Hantverk");
INSERT INTO nameTable (id,item) VALUES (249,"Fordon");
INSERT INTO nameTable (id,item) VALUES (250,"Reparera");
INSERT INTO nameTable (id,item) VALUES (251,"Typer");
INSERT INTO nameTable (id,item) VALUES (252,"Bilar");
INSERT INTO nameTable (id,item) VALUES (253,"Motorcyklar");
INSERT INTO nameTable (id,item) VALUES (254,"Fyrhjulingar");
INSERT INTO nameTable (id,item) VALUES (255,"Husvagnar");
INSERT INTO nameTable (id,item) VALUES (256,"Lastbilar");
INSERT INTO nameTable (id,item) VALUES (257,"Vattenscooter");
INSERT INTO nameTable (id,item) VALUES (258,"Gamla");
INSERT INTO nameTable (id,item) VALUES (259,"Lyx");
INSERT INTO nameTable (id,item) VALUES (260,"Exotisk");
INSERT INTO nameTable (id,item) VALUES (261,"Staden");
INSERT INTO nameTable (id,item) VALUES (262,"Regering");
INSERT INTO nameTable (id,item) VALUES (263,"Ekonomi");
INSERT INTO nameTable (id,item) VALUES (264,"Marknad");
INSERT INTO nameTable (id,item) VALUES (265,"Utbilding");
INSERT INTO nameTable (id,item) VALUES (266,"Arbetsplats");
INSERT INTO nameTable (id,item) VALUES (267,"Underhållning");
INSERT INTO nameTable (id,item) VALUES (268,"Boende");
INSERT INTO nameTable (id,item) VALUES (269,"Kulturer");
INSERT INTO nameTable (id,item) VALUES (270,"Turist");
INSERT INTO nameTable (id,item) VALUES (271,"Advokat");
INSERT INTO nameTable (id,item) VALUES (272,"Ambassad");
INSERT INTO nameTable (id,item) VALUES (273,"Kommun");
INSERT INTO nameTable (id,item) VALUES (274,"Lokalförvaltningskontor");
INSERT INTO nameTable (id,item) VALUES (275,"Tingshuspolisen");
INSERT INTO nameTable (id,item) VALUES (276,"Försäkring");
INSERT INTO nameTable (id,item) VALUES (277,"Resebyrå");
INSERT INTO nameTable (id,item) VALUES (278,"Bank");
INSERT INTO nameTable (id,item) VALUES (279,"ATM");
INSERT INTO nameTable (id,item) VALUES (280,"Köpcentrum");
INSERT INTO nameTable (id,item) VALUES (281,"Bokföring");
INSERT INTO nameTable (id,item) VALUES (282,"Postkontor");
INSERT INTO nameTable (id,item) VALUES (283,"Supermarket");
INSERT INTO nameTable (id,item) VALUES (284,"Butik");
INSERT INTO nameTable (id,item) VALUES (285,"Varuhus");
INSERT INTO nameTable (id,item) VALUES (286,"Bageri");
INSERT INTO nameTable (id,item) VALUES (287,"Tvätt");
INSERT INTO nameTable (id,item) VALUES (288,"Skoaffär");
INSERT INTO nameTable (id,item) VALUES (289,"Bilförsäljare");
INSERT INTO nameTable (id,item) VALUES (290,"Bar");
INSERT INTO nameTable (id,item) VALUES (291,"Cafeteria");
INSERT INTO nameTable (id,item) VALUES (292,"Resturang");
INSERT INTO nameTable (id,item) VALUES (293,"Takeaway");
INSERT INTO nameTable (id,item) VALUES (294,"Matleverans");
INSERT INTO nameTable (id,item) VALUES (295,"Bibliotek");
INSERT INTO nameTable (id,item) VALUES (296,"Universitet");
INSERT INTO nameTable (id,item) VALUES (297,"Grundskola");
INSERT INTO nameTable (id,item) VALUES (298,"Gymnasieskola");
INSERT INTO nameTable (id,item) VALUES (299,"Bokaffär");
INSERT INTO nameTable (id,item) VALUES (300,"Låssmed");
INSERT INTO nameTable (id,item) VALUES (301,"Takentreprenör");
INSERT INTO nameTable (id,item) VALUES (302,"Elektriker");
INSERT INTO nameTable (id,item) VALUES (303,"Flyttare");
INSERT INTO nameTable (id,item) VALUES (304,"Järnaffär");
INSERT INTO nameTable (id,item) VALUES (305,"Bensinstation");
INSERT INTO nameTable (id,item) VALUES (306,"Målare");
INSERT INTO nameTable (id,item) VALUES (307,"Reparation");
INSERT INTO nameTable (id,item) VALUES (308,"Kontor");
INSERT INTO nameTable (id,item) VALUES (309,"Datoringengör arbetsplats");
INSERT INTO nameTable (id,item) VALUES (310,"Casino");
INSERT INTO nameTable (id,item) VALUES (311,"Bio");
INSERT INTO nameTable (id,item) VALUES (312,"Night Club");
INSERT INTO nameTable (id,item) VALUES (313,"Stadium");
INSERT INTO nameTable (id,item) VALUES (314,"Filmuthyrning");
INSERT INTO nameTable (id,item) VALUES (315,"Gym");
INSERT INTO nameTable (id,item) VALUES (316,"Fastighetsbyrå");
INSERT INTO nameTable (id,item) VALUES (317,"Förråd");
INSERT INTO nameTable (id,item) VALUES (318,"Begravningsbyrå");
INSERT INTO nameTable (id,item) VALUES (319,"Kyrkogård");
INSERT INTO nameTable (id,item) VALUES (320,"Hotell");
INSERT INTO nameTable (id,item) VALUES (321,"Vandrarhem");
INSERT INTO nameTable (id,item) VALUES (322,"Camping");
INSERT INTO nameTable (id,item) VALUES (323,"Konstgalleri");
INSERT INTO nameTable (id,item) VALUES (324,"Museum");
INSERT INTO nameTable (id,item) VALUES (325,"Kyrka");
INSERT INTO nameTable (id,item) VALUES (326,"Synagoga");
INSERT INTO nameTable (id,item) VALUES (327,"Nöjespark");
INSERT INTO nameTable (id,item) VALUES (328,"Aquarium");
INSERT INTO nameTable (id,item) VALUES (329,"Park");
INSERT INTO nameTable (id,item) VALUES (330,"Camping");
INSERT INTO nameTable (id,item) VALUES (331,"Zoo");
INSERT INTO nameTable (id,item) VALUES (332,"Transport");
INSERT INTO nameTable (id,item) VALUES (333,"Hälsa");
INSERT INTO nameTable (id,item) VALUES (334,"Flygplatsbiluthyrning");
INSERT INTO nameTable (id,item) VALUES (335,"Biltvättstation");
INSERT INTO nameTable (id,item) VALUES (336,"Veterinärsvård");
INSERT INTO nameTable (id,item) VALUES (337,"Tandläkare");
INSERT INTO nameTable (id,item) VALUES (338,"Läkare");
INSERT INTO nameTable (id,item) VALUES (339,"Apotek");
INSERT INTO nameTable (id,item) VALUES (340,"Fysioterapeut");
INSERT INTO nameTable (id,item) VALUES (341,"Sjukhus");
INSERT INTO nameTable (id,item) VALUES (342,"Hemma");
INSERT INTO nameTable (id,item) VALUES (343,"Nivåer");
INSERT INTO nameTable (id,item) VALUES (344,"Rum");
INSERT INTO nameTable (id,item) VALUES (345,"Sovrum");
INSERT INTO nameTable (id,item) VALUES (346,"Badrum");
INSERT INTO nameTable (id,item) VALUES (347,"Kök");
INSERT INTO nameTable (id,item) VALUES (348,"Mottagande hall");
INSERT INTO nameTable (id,item) VALUES (349,"Hemmakontor");
INSERT INTO nameTable (id,item) VALUES (350,"Vardagsrum");
INSERT INTO nameTable (id,item) VALUES (351,"Andra hemutbygnader");
INSERT INTO nameTable (id,item) VALUES (352,"hall");
INSERT INTO nameTable (id,item) VALUES (353,"Källare");
INSERT INTO nameTable (id,item) VALUES (354,"Skorsten");
INSERT INTO nameTable (id,item) VALUES (355,"Tak");
INSERT INTO nameTable (id,item) VALUES (356,"Vägg");
INSERT INTO nameTable (id,item) VALUES (357,"Skåp");
INSERT INTO nameTable (id,item) VALUES (358,"Stol");
INSERT INTO nameTable (id,item) VALUES (359,"Matta");
INSERT INTO nameTable (id,item) VALUES (360,"Lampa");
INSERT INTO nameTable (id,item) VALUES (361,"Fönster");
INSERT INTO nameTable (id,item) VALUES (362,"Bord");
INSERT INTO nameTable (id,item) VALUES (363,"Dator");
INSERT INTO nameTable (id,item) VALUES (364,"Musikuthyrning");
INSERT INTO nameTable (id,item) VALUES (365,"Sänghyllor");
INSERT INTO nameTable (id,item) VALUES (366,"Nattduksbord");
INSERT INTO nameTable (id,item) VALUES (367,"Gaderob");
INSERT INTO nameTable (id,item) VALUES (368,"Skrivbordslampa");
INSERT INTO nameTable (id,item) VALUES (369,"Väckarklocka");
INSERT INTO nameTable (id,item) VALUES (370,"Toalett");
INSERT INTO nameTable (id,item) VALUES (371,"Dusch");
INSERT INTO nameTable (id,item) VALUES (372,"Bad");
INSERT INTO nameTable (id,item) VALUES (373,"Handfat");
INSERT INTO nameTable (id,item) VALUES (374,"Kylskåp");
INSERT INTO nameTable (id,item) VALUES (375,"Ugn");
INSERT INTO nameTable (id,item) VALUES (376,"Mikrovågsugn");
INSERT INTO nameTable (id,item) VALUES (377,"Diskmaskin");
INSERT INTO nameTable (id,item) VALUES (378,"Spisar");
INSERT INTO nameTable (id,item) VALUES (379,"Kåpor-kök");
INSERT INTO nameTable (id,item) VALUES (380,"Krukor");
INSERT INTO nameTable (id,item) VALUES (381,"Glas+Bestick");
INSERT INTO nameTable (id,item) VALUES (382,"Mat");
INSERT INTO nameTable (id,item) VALUES (383,"Matsal");
INSERT INTO nameTable (id,item) VALUES (384,"Dörrmatta");
INSERT INTO nameTable (id,item) VALUES (385,"Klädhylla");
INSERT INTO nameTable (id,item) VALUES (386,"Kommod");
INSERT INTO nameTable (id,item) VALUES (387,"Spegel");
INSERT INTO nameTable (id,item) VALUES (388,"Korridor");
INSERT INTO nameTable (id,item) VALUES (389,"Matta");
INSERT INTO nameTable (id,item) VALUES (390,"TV");
INSERT INTO nameTable (id,item) VALUES (391,"Soffa");
INSERT INTO nameTable (id,item) VALUES (392,"Böcker");
INSERT INTO nameTable (id,item) VALUES (393,"Vas");
INSERT INTO nameTable (id,item) VALUES (394,"Bilder");
INSERT INTO nameTable (id,item) VALUES (395,"Växter(Krukväxter)");
INSERT INTO nameTable (id,item) VALUES (396,"Trädgård");
INSERT INTO nameTable (id,item) VALUES (397,"Pool");
INSERT INTO nameTable (id,item) VALUES (398,"Vindsterrass");
INSERT INTO nameTable (id,item) VALUES (399,"Förråd");
INSERT INTO nameTable (id,item) VALUES (400,"Balkong");
INSERT INTO nameTable (id,item) VALUES (401,"Förvaltning(Administration)");
INSERT INTO nameTable (id,item) VALUES (402,"Vattenfallsmetoden");
INSERT INTO nameTable (id,item) VALUES (403,"Kravspecifikation");
INSERT INTO nameTable (id,item) VALUES (404,"Design");
INSERT INTO nameTable (id,item) VALUES (405,"Konstruktion");
INSERT INTO nameTable (id,item) VALUES (406,"Integration");
INSERT INTO nameTable (id,item) VALUES (407,"Test");
INSERT INTO nameTable (id,item) VALUES (408,"Installation");
INSERT INTO nameTable (id,item) VALUES (409,"Underhåll");
INSERT INTO nameTable (id,item) VALUES (410,"Mjukvaror");
INSERT INTO nameTable (id,item) VALUES (411,"Mjukvaruprojekt");
INSERT INTO nameTable (id,item) VALUES (412,"Spel och datorspel");
INSERT INTO nameTable (id,item) VALUES (413,"Fysisk kondition");
INSERT INTO nameTable (id,item) VALUES (414,"Överlevnad");
INSERT INTO nameTable (id,item) VALUES (415,"Ätbart");
INSERT INTO nameTable (id,item) VALUES (416,"Hasardspel");
INSERT INTO nameTable (id,item) VALUES (417,"Kortspel");
INSERT INTO nameTable (id,item) VALUES (418,"Spelautomater");
INSERT INTO nameTable (id,item) VALUES (419,"Lotteri");
INSERT INTO nameTable (id,item) VALUES (420,"Kasinomarker(Kasinochips)");
INSERT INTO nameTable (id,item) VALUES (421,"Lotteribiljetter");
INSERT INTO nameTable (id,item) VALUES (422,"Spådom");
INSERT INTO nameTable (id,item) VALUES (423,"Astrologi");
INSERT INTO nameTable (id,item) VALUES (424,"Stjärntecken");
INSERT INTO nameTable (id,item) VALUES (425,"Oxen");
INSERT INTO nameTable (id,item) VALUES (426,"Tvillingarna");
INSERT INTO nameTable (id,item) VALUES (427,"Kräftan");
INSERT INTO nameTable (id,item) VALUES (428,"Lejonet");
INSERT INTO nameTable (id,item) VALUES (429,"Jungfrun");
INSERT INTO nameTable (id,item) VALUES (430,"Vågen");
INSERT INTO nameTable (id,item) VALUES (431,"Skorpionen");
INSERT INTO nameTable (id,item) VALUES (432,"Skytten");
INSERT INTO nameTable (id,item) VALUES (433,"Stenbocken");
INSERT INTO nameTable (id,item) VALUES (434,"Vattumannen");
INSERT INTO nameTable (id,item) VALUES (435,"Fiskarna");
INSERT INTO nameTable (id,item) VALUES (436,"Tarot");
INSERT INTO nameTable (id,item) VALUES (437,"Astronomi");
INSERT INTO nameTable (id,item) VALUES (438,"Stel mekanik");
INSERT INTO nameTable (id,item) VALUES (439,"Vätskemekanik");
INSERT INTO nameTable (id,item) VALUES (440,"Elektricitet");
INSERT INTO nameTable (id,item) VALUES (441,"Vågor");
INSERT INTO nameTable (id,item) VALUES (442,"Termodynamik(Värme)");
INSERT INTO nameTable (id,item) VALUES (443,"Kärnfysik(Atomer)");
INSERT INTO nameTable (id,item) VALUES (444,"P=E/t");
INSERT INTO nameTable (id,item) VALUES (445,"E=F*s");
INSERT INTO nameTable (id,item) VALUES (446,"F=GMm/r²");
INSERT INTO nameTable (id,item) VALUES (447,"F=ma");
INSERT INTO nameTable (id,item) VALUES (448,"τ=Fr*sin(α)");
INSERT INTO nameTable (id,item) VALUES (449,"τ=Iα");
INSERT INTO nameTable (id,item) VALUES (450,"Laminär");
INSERT INTO nameTable (id,item) VALUES (451,"Turbulens");
INSERT INTO nameTable (id,item) VALUES (452,"ρ=mV");
INSERT INTO nameTable (id,item) VALUES (453,"F1A1=F2A2");
INSERT INTO nameTable (id,item) VALUES (454,"Q=dVdt");
INSERT INTO nameTable (id,item) VALUES (455,"A1v1=A2v2");
INSERT INTO nameTable (id,item) VALUES (456,"P=IV");
INSERT INTO nameTable (id,item) VALUES (457,"F=qvB*sin(α)");
INSERT INTO nameTable (id,item) VALUES (458,"ΣU=ΣIR");
INSERT INTO nameTable (id,item) VALUES (459,"Q=CV");
INSERT INTO nameTable (id,item) VALUES (460,"τ=RC");
INSERT INTO nameTable (id,item) VALUES (461,"ε=Φ/t");
INSERT INTO nameTable (id,item) VALUES (462,"F=-kx");
INSERT INTO nameTable (id,item) VALUES (463,"I=P/A");
INSERT INTO nameTable (id,item) VALUES (464,"1/o + 1/i = 1/f");
INSERT INTO nameTable (id,item) VALUES (465,"Reflektion");
INSERT INTO nameTable (id,item) VALUES (466,"Refraktion");
INSERT INTO nameTable (id,item) VALUES (467,"Diffraktion");
INSERT INTO nameTable (id,item) VALUES (468,"n*sin(α)");
INSERT INTO nameTable (id,item) VALUES (469,"d*sin(α)=mλ");
INSERT INTO nameTable (id,item) VALUES (470,"Ekonomi");
INSERT INTO nameTable (id,item) VALUES (471,"Handel");
INSERT INTO nameTable (id,item) VALUES (472,"Politik");
INSERT INTO nameTable (id,item) VALUES (473,"Flöde");
INSERT INTO nameTable (id,item) VALUES (474,"Tre stora branscher");
INSERT INTO nameTable (id,item) VALUES (475,"Inkomst");
INSERT INTO nameTable (id,item) VALUES (476,"Utgifter");
INSERT INTO nameTable (id,item) VALUES (477,"Kontanter");
INSERT INTO nameTable (id,item) VALUES (478,"Terminskontrakt(Futures)");
INSERT INTO nameTable (id,item) VALUES (479,"Aktie(Stock)");
INSERT INTO nameTable (id,item) VALUES (480,"Kryptovaluta");
INSERT INTO nameTable (id,item) VALUES (481,"Korruption");
INSERT INTO nameTable (id,item) VALUES (482,"Neptism");
INSERT INTO nameTable (id,item) VALUES (483,"Mutor");
INSERT INTO nameTable (id,item) VALUES (484,"Förskingring");
INSERT INTO nameTable (id,item) VALUES (485,"Klassisk ekonomi");
INSERT INTO nameTable (id,item) VALUES (486,"Neoklassisk ekonomi");
INSERT INTO nameTable (id,item) VALUES (487,"1");
INSERT INTO nameTable (id,item) VALUES (488,"1½");
INSERT INTO nameTable (id,item) VALUES (489,"2");
INSERT INTO nameTable (id,item) VALUES (490,"3");
INSERT INTO nameTable (id,item) VALUES (491,"Jordbruk");
INSERT INTO nameTable (id,item) VALUES (492,"Skogsbruk");
INSERT INTO nameTable (id,item) VALUES (493,"Fiske");
INSERT INTO nameTable (id,item) VALUES (494,"Gruvdrift");
INSERT INTO nameTable (id,item) VALUES (495,"Arbetskraft");
INSERT INTO nameTable (id,item) VALUES (496,"Råvaror");
INSERT INTO nameTable (id,item) VALUES (497,"Kunder");
INSERT INTO nameTable (id,item) VALUES (498,"Industri Specialisering");
INSERT INTO nameTable (id,item) VALUES (499,"Livsmedelindustri");
INSERT INTO nameTable (id,item) VALUES (500,"Skogsindustri");
INSERT INTO nameTable (id,item) VALUES (501,"Jord-sten");
INSERT INTO nameTable (id,item) VALUES (502,"Tekoindustri");
INSERT INTO nameTable (id,item) VALUES (503,"Kemiindustri");
INSERT INTO nameTable (id,item) VALUES (504,"Information och tjänster");
INSERT INTO nameTable (id,item) VALUES (505,"Turism");
INSERT INTO nameTable (id,item) VALUES (506,"Handel");
INSERT INTO nameTable (id,item) VALUES (507,"Världshandel");
INSERT INTO nameTable (id,item) VALUES (508,"EU");
INSERT INTO nameTable (id,item) VALUES (509,"NAFTA");
INSERT INTO nameTable (id,item) VALUES (510,"MERCOSUR");
INSERT INTO nameTable (id,item) VALUES (511,"WTO");
INSERT INTO nameTable (id,item) VALUES (512,"Application");
INSERT INTO nameTable (id,item) VALUES (513,"I/O (Input/Output)");
INSERT INTO nameTable (id,item) VALUES (514,"Memory");
INSERT INTO nameTable (id,item) VALUES (515,"Disk");
INSERT INTO nameTable (id,item) VALUES (516,"OS (Operativsystem)");
INSERT INTO nameTable (id,item) VALUES (517,"Kallt vapen");
INSERT INTO nameTable (id,item) VALUES (518,"Hett vapen");
INSERT INTO nameTable (id,item) VALUES (519,"Kärnvapen");
INSERT INTO nameTable (id,item) VALUES (520,"Kemivapen");
INSERT INTO nameTable (id,item) VALUES (521,"Biologivapen");
INSERT INTO nameTable (id,item) VALUES (522,"Pappersverk");
INSERT INTO nameTable (id,item) VALUES (523,"Sågverk");
INSERT INTO nameTable (id,item) VALUES (524,"Rasterisering");
INSERT INTO nameTable (id,item) VALUES (525,"Vetenskaplig Rasterisering");
INSERT INTO nameTable (id,item) VALUES (526,"(x-x0)²+(y-y0)²=r²");
INSERT INTO nameTable (id,item) VALUES (527,"Applikation");
INSERT INTO nameTable (id,item) VALUES (528,"Politisk inriktningar");
INSERT INTO nameTable (id,item) VALUES (529,"Anarkistisk");
INSERT INTO nameTable (id,item) VALUES (530,"Marxist");
INSERT INTO nameTable (id,item) VALUES (531,"Socialistisk");
INSERT INTO nameTable (id,item) VALUES (532,"Liberal");
INSERT INTO nameTable (id,item) VALUES (533,"Konsvervativ");
INSERT INTO nameTable (id,item) VALUES (534,"Monarkistisk");
INSERT INTO nameTable (id,item) VALUES (535,"Fascist");
INSERT INTO nameTable (id,item) VALUES (536,"Svensk politik");
INSERT INTO nameTable (id,item) VALUES (537,"Amerikansk politik");
INSERT INTO nameTable (id,item) VALUES (538,"Statsnivå");
INSERT INTO nameTable (id,item) VALUES (539,"Landstingsnivå (Regionalnivå)");
INSERT INTO nameTable (id,item) VALUES (540,"Kommunalnivå");
INSERT INTO nameTable (id,item) VALUES (541,"Riksdagen");
INSERT INTO nameTable (id,item) VALUES (542,"Regeringen");
INSERT INTO nameTable (id,item) VALUES (543,"Statsministern");
INSERT INTO nameTable (id,item) VALUES (544,"Estetik");
INSERT INTO nameTable (id,item) VALUES (545,"Språk");
INSERT INTO nameTable (id,item) VALUES (546,"Diskussioner");
INSERT INTO nameTable (id,item) VALUES (547,"Utskott");
INSERT INTO nameTable (id,item) VALUES (548,"Departement");
INSERT INTO nameTable (id,item) VALUES (549,"Utrikesdepartement");
INSERT INTO nameTable (id,item) VALUES (550,"Utför besult");
INSERT INTO nameTable (id,item) VALUES (551,"Statliga uppgifter");
INSERT INTO nameTable (id,item) VALUES (552,"Partier");
INSERT INTO nameTable (id,item) VALUES (553,"Kongressen");
INSERT INTO nameTable (id,item) VALUES (554,"Senaten");
INSERT INTO nameTable (id,item) VALUES (555,"Högsta domstolen");
INSERT INTO nameTable (id,item) VALUES (556,"Partier");
INSERT INTO nameTable (id,item) VALUES (557,"Demokraterna");
INSERT INTO nameTable (id,item) VALUES (558,"Republikanerna");
INSERT INTO nameTable (id,item) VALUES (559,"Demografi");
INSERT INTO nameTable (id,item) VALUES (560,"Geografi-politik");
INSERT INTO nameTable (id,item) VALUES (561,"4 Stadier");
INSERT INTO nameTable (id,item) VALUES (562,"Hög föddantal och hög dödsantal");
INSERT INTO nameTable (id,item) VALUES (563,"Hög föddantal och låg dödsantal");
INSERT INTO nameTable (id,item) VALUES (564,"Låg föddantal och låg dödsantal");
INSERT INTO nameTable (id,item) VALUES (565,"Jämn fördelning");
INSERT INTO nameTable (id,item) VALUES (566,"Förflyttning");
INSERT INTO nameTable (id,item) VALUES (567,"Arbete");
INSERT INTO nameTable (id,item) VALUES (568,"Krig");
INSERT INTO nameTable (id,item) VALUES (569,"Förföljelse");
INSERT INTO nameTable (id,item) VALUES (570,"Miljö");
INSERT INTO nameTable (id,item) VALUES (571,"Geografi-ekonomi");
INSERT INTO nameTable (id,item) VALUES (572,"Levnadsstandard (HDI)");
INSERT INTO nameTable (id,item) VALUES (573,"Kapitalism");
INSERT INTO nameTable (id,item) VALUES (574,"Fattigdom");
INSERT INTO nameTable (id,item) VALUES (575,"Idealsamhälle");
INSERT INTO nameTable (id,item) VALUES (576,"Stora ekonomiska klyftor");
INSERT INTO nameTable (id,item) VALUES (577,"Orättvisa villkor");
INSERT INTO nameTable (id,item) VALUES (578,"Resurser bland rika");
INSERT INTO nameTable (id,item) VALUES (579,"Världshandeln gynnar rika");
INSERT INTO nameTable (id,item) VALUES (580,"Sjukdom");
INSERT INTO nameTable (id,item) VALUES (581,"Korruption");
INSERT INTO nameTable (id,item) VALUES (582,"Brist");
INSERT INTO nameTable (id,item) VALUES (583,"Högt befolkad");
INSERT INTO nameTable (id,item) VALUES (584,"Svält");
INSERT INTO nameTable (id,item) VALUES (585,"Jordbrukssamhälle");
INSERT INTO nameTable (id,item) VALUES (586,"Vattenbrist");
INSERT INTO nameTable (id,item) VALUES (587,"Lösningar");
INSERT INTO nameTable (id,item) VALUES (588,"Millenniemål");
INSERT INTO nameTable (id,item) VALUES (589,"Agenda 2030");
INSERT INTO nameTable (id,item) VALUES (590,"Länder");
INSERT INTO nameTable (id,item) VALUES (591,"Konst");
INSERT INTO nameTable (id,item) VALUES (592,"Design");
INSERT INTO nameTable (id,item) VALUES (593,"Litteratur");
INSERT INTO nameTable (id,item) VALUES (594,"Musik");
INSERT INTO nameTable (id,item) VALUES (595,"Arkitektur");
INSERT INTO nameTable (id,item) VALUES (596,"USA");
INSERT INTO nameTable (id,item) VALUES (597,"Japan");
INSERT INTO nameTable (id,item) VALUES (598,"Ryssland");
INSERT INTO nameTable (id,item) VALUES (599,"Bergskedjor vid kuster");
INSERT INTO nameTable (id,item) VALUES (600,"Inre slätter");
INSERT INTO nameTable (id,item) VALUES (601,"Floder");
INSERT INTO nameTable (id,item) VALUES (602,"Översvämningar");
INSERT INTO nameTable (id,item) VALUES (603,"Skolan");
INSERT INTO nameTable (id,item) VALUES (604,"Arbete");
INSERT INTO nameTable (id,item) VALUES (605,"Resa");
INSERT INTO nameTable (id,item) VALUES (606,"Underhållning");
INSERT INTO nameTable (id,item) VALUES (607,"Hobby");
INSERT INTO nameTable (id,item) VALUES (608,"Livsstil");
INSERT INTO nameTable (id,item) VALUES (609,"Privatliv");
INSERT INTO nameTable (id,item) VALUES (610,"Avkopplande Miami");
INSERT INTO nameTable (id,item) VALUES (611,"Modernt");
INSERT INTO nameTable (id,item) VALUES (612,"Klassiskt");
INSERT INTO nameTable (id,item) VALUES (613,"Lantlig");
INSERT INTO nameTable (id,item) VALUES (614,"Sommar");
INSERT INTO nameTable (id,item) VALUES (615,"Vanligt liv");
INSERT INTO nameTable (id,item) VALUES (616,"Tonåringar");
INSERT INTO nameTable (id,item) VALUES (617,"Mot framsteg(bråkmakare)");
INSERT INTO nameTable (id,item) VALUES (618,"Rayan");
INSERT INTO nameTable (id,item) VALUES (619,"Rayan Produktivitet");
INSERT INTO nameTable (id,item) VALUES (620,"Datorspel-livsstil");
INSERT INTO nameTable (id,item) VALUES (621,"Framtidslivsstil");
INSERT INTO nameTable (id,item) VALUES (622,"Minimalism");
INSERT INTO nameTable (id,item) VALUES (623,"metodik");
INSERT INTO nameTable (id,item) VALUES (624,"Tiago-PZK metoden");
INSERT INTO nameTable (id,item) VALUES (625,"Vanlig inlärningsmetoden");
INSERT INTO nameTable (id,item) VALUES (626,"AOORA struktur");
INSERT INTO nameTable (id,item) VALUES (627,"[1 2 3 4 5 6]");
INSERT INTO nameTable (id,item) VALUES (628,"[a1 a2 a3 a4 a5 a6]");
INSERT INTO nameTable (id,item) VALUES (629,"Översikt");
INSERT INTO nameTable (id,item) VALUES (630,"Kunskap");
INSERT INTO nameTable (id,item) VALUES (631,"Med andra");
INSERT INTO nameTable (id,item) VALUES (632,"Profil för samhälle");
INSERT INTO nameTable (id,item) VALUES (633,"Skolämnen");
INSERT INTO nameTable (id,item) VALUES (634,"Träslöjd");
INSERT INTO nameTable (id,item) VALUES (635,"Svenska");
INSERT INTO nameTable (id,item) VALUES (636,"Engelska");
INSERT INTO nameTable (id,item) VALUES (637,"Franska");
INSERT INTO nameTable (id,item) VALUES (638,"Skolämnen");
INSERT INTO nameTable (id,item) VALUES (639,"Uppgifter");
INSERT INTO nameTable (id,item) VALUES (640,"Förhör och prov");
INSERT INTO nameTable (id,item) VALUES (641,"Inga genvägar i skolan");
INSERT INTO nameTable (id,item) VALUES (642,"Aktiviteter");
INSERT INTO nameTable (id,item) VALUES (643,"Grupparbete");
INSERT INTO nameTable (id,item) VALUES (644,"Utflykt");
INSERT INTO nameTable (id,item) VALUES (645,"Studiebesök");
INSERT INTO nameTable (id,item) VALUES (646,"Personer");
INSERT INTO nameTable (id,item) VALUES (647,"Förberedelser");
INSERT INTO nameTable (id,item) VALUES (648,"Struktur (Plan)");
INSERT INTO nameTable (id,item) VALUES (649,"Under resan");
INSERT INTO nameTable (id,item) VALUES (650,"Vart");
INSERT INTO nameTable (id,item) VALUES (651,"Vem");
INSERT INTO nameTable (id,item) VALUES (652,"Hur");
INSERT INTO nameTable (id,item) VALUES (653,"När");
INSERT INTO nameTable (id,item) VALUES (654,"Okända länder");
INSERT INTO nameTable (id,item) VALUES (655,"Kunskap");
INSERT INTO nameTable (id,item) VALUES (656,"Sport");
INSERT INTO nameTable (id,item) VALUES (657,"Natur");
INSERT INTO nameTable (id,item) VALUES (658,"Kultur");
INSERT INTO nameTable (id,item) VALUES (659,"Familj");
INSERT INTO nameTable (id,item) VALUES (660,"Vänner");
INSERT INTO nameTable (id,item) VALUES (661,"Använder pengar");
INSERT INTO nameTable (id,item) VALUES (662,"För mat");
INSERT INTO nameTable (id,item) VALUES (663,"Hur ska man åka?");
INSERT INTO nameTable (id,item) VALUES (664,"Budget");
INSERT INTO nameTable (id,item) VALUES (665,"Transport");
INSERT INTO nameTable (id,item) VALUES (666,"Överlevnad");
INSERT INTO nameTable (id,item) VALUES (667,"Boende");
INSERT INTO nameTable (id,item) VALUES (668,"Resebyrå");
INSERT INTO nameTable (id,item) VALUES (669,"Problem under resan");
INSERT INTO nameTable (id,item) VALUES (670,"Sport");
INSERT INTO nameTable (id,item) VALUES (671,"Struktur");
INSERT INTO nameTable (id,item) VALUES (672,"Typer");
INSERT INTO nameTable (id,item) VALUES (673,"Lag");
INSERT INTO nameTable (id,item) VALUES (674,"Strategi");
INSERT INTO nameTable (id,item) VALUES (675,"Träning");
INSERT INTO nameTable (id,item) VALUES (676,"Kommunikation");
INSERT INTO nameTable (id,item) VALUES (677,"Konversation");
INSERT INTO nameTable (id,item) VALUES (678,"Skämt");
INSERT INTO nameTable (id,item) VALUES (679,"Börjar konversation");
INSERT INTO nameTable (id,item) VALUES (680,"Ändra prattema");
INSERT INTO nameTable (id,item) VALUES (681,"Presentationer");
INSERT INTO nameTable (id,item) VALUES (682,"Psykologi");
INSERT INTO nameTable (id,item) VALUES (683,"Åsikter och tankar");
INSERT INTO nameTable (id,item) VALUES (684,"Rayan kompetens");
INSERT INTO nameTable (id,item) VALUES (685,"3-allt-metoden");
INSERT INTO nameTable (id,item) VALUES (686,"Döda alla");
INSERT INTO nameTable (id,item) VALUES (687,"Bränn allt");
INSERT INTO nameTable (id,item) VALUES (688,"Plundra allt");
INSERT INTO nameTable (id,item) VALUES (689,"Personlighet(Karaktär)");
INSERT INTO nameTable (id,item) VALUES (690,"Modig");
INSERT INTO nameTable (id,item) VALUES (691,"Äventyrlig");
INSERT INTO nameTable (id,item) VALUES (692,"Feg");
INSERT INTO nameTable (id,item) VALUES (693,"Självständig");
INSERT INTO nameTable (id,item) VALUES (694,"Bra karaktär");
INSERT INTO nameTable (id,item) VALUES (695,"Dåliga karaktär");
INSERT INTO nameTable (id,item) VALUES (696,"Resurskrik");
INSERT INTO nameTable (id,item) VALUES (697,"Framgångsrik");
INSERT INTO nameTable (id,item) VALUES (698,"Skicklig");
INSERT INTO nameTable (id,item) VALUES (699,"Fantasifull");
INSERT INTO nameTable (id,item) VALUES (700,"Kreativ");
INSERT INTO nameTable (id,item) VALUES (701,"Nyfiken");
INSERT INTO nameTable (id,item) VALUES (702,"Ödmjuk");
INSERT INTO nameTable (id,item) VALUES (703,"Respektfull");
INSERT INTO nameTable (id,item) VALUES (704,"Artig");
INSERT INTO nameTable (id,item) VALUES (705,"Pålitlig");
INSERT INTO nameTable (id,item) VALUES (706,"Ärlig");
INSERT INTO nameTable (id,item) VALUES (707,"Generös");
INSERT INTO nameTable (id,item) VALUES (708,"Lojal");
INSERT INTO nameTable (id,item) VALUES (709,"Patrotisk");
INSERT INTO nameTable (id,item) VALUES (710,"Neutrala karaktär");
INSERT INTO nameTable (id,item) VALUES (711,"Strikt");
INSERT INTO nameTable (id,item) VALUES (712,"Dominerande");
INSERT INTO nameTable (id,item) VALUES (713,"Ledare");
INSERT INTO nameTable (id,item) VALUES (714,"Energisk");
INSERT INTO nameTable (id,item) VALUES (715,"Hoppfull");
INSERT INTO nameTable (id,item) VALUES (716,"Utåtriktad");
INSERT INTO nameTable (id,item) VALUES (717,"Introvert");
INSERT INTO nameTable (id,item) VALUES (718,"Allvarlig");
INSERT INTO nameTable (id,item) VALUES (719,"Lugn");
INSERT INTO nameTable (id,item) VALUES (720,"Ensam");
INSERT INTO nameTable (id,item) VALUES (721,"Blyg");
INSERT INTO nameTable (id,item) VALUES (722,"Lat");
INSERT INTO nameTable (id,item) VALUES (723,"Stygg");
INSERT INTO nameTable (id,item) VALUES (724,"Slughet");
INSERT INTO nameTable (id,item) VALUES (725,"Listig");
INSERT INTO nameTable (id,item) VALUES (726,"Oförskämd");
INSERT INTO nameTable (id,item) VALUES (727,"Självisk");
INSERT INTO nameTable (id,item) VALUES (728,"Envis");
INSERT INTO nameTable (id,item) VALUES (729,"Våldsam(Utåtagerande)");
INSERT INTO nameTable (id,item) VALUES (730,"Materalist");
INSERT INTO nameTable (id,item) VALUES (731,"Girig");
INSERT INTO nameTable (id,item) VALUES (732,"Oärlig");
INSERT INTO nameTable (id,item) VALUES (733,"Grinig");
INSERT INTO nameTable (id,item) VALUES (734,"Deprimerad");
INSERT INTO nameTable (id,item) VALUES (735,"Eländig");
INSERT INTO nameTable (id,item) VALUES (736,"Livet");
