vocabulary = [
    ["Cancerous", "Carcinogenic"],
    ["Charged with", "Indicted"],
    ["Crooner", "Vocalist"],
    ["Examined", "Probed"],
    ["Uprooted", "Displaced"],
    ["Provoking", "Inciting"],
    ["Kindling", "Ignition"],
    ["Heart-breaking", "Heart-wrenching"],
    ["Supposed", "Alledged"],
    ["Half-island", "Peninsula"],
    ["Ending", "Abating"],
    ["Approvals", "Ratifications"],
    ["Prophetic (Catastrophic)", "Apocalyptic"],
    ["Meddling with", "Impending"],
    ["Annoyed", "Disgruntled"],
    ["Pup", "Pooch"],
    ["First (virgin)", "Maiden"],
    ["Toxins", "Contaminants"],
    ["Executioner", "Assassin"],
    ["Comfort (peace)", "Solace"],
    ["Describe", "Depicts"],
    ["Crossbread", "Mongrel"],
    ["Stained", "Sullied"],
    ["Indication", "Harbinger"],
    ["Ocean liner (tanker)", "Cargo ship, vessel"],
    ["Cruelness", "Atrocities"],
    ["Essentially (Truly)", "Vitally"],
    ["Resource", "Asset"],
    ["A large number of", "A slew"],
    ["Encircling", "Encompassing"],
    ["More than", "In excess of"],
    ["Chaos", "Turmoil"],
    ["Detstroyed", "Eradicated"],
    ["Causing Chaos", "Wreaking havoc"],
    ["Eminent (distinguished)", "Prestigious"],
    ["Indefinite", "Tentative"],
    ["Unpredictable", "Arbitary"]
]